### ISSUE TITLE
Connection refused when restarting kodi with home widget activated

### ISSUE THREAD

**Issue by im85288** [asciidisco/plugin.video.netflix#196]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
When you add an entry to home widgets, occasionally when restarting kodi an error is shown. Delving into this deeper it looks like a connection refused error occurs because the netflix addon is not ready?

### Prerequisites
Add a widget link with skin shortcuts (such as continue watching) and restart kodi
* [x] Are you running the latest version?

### Description

The following is the log of the error:

`14:07:41.868 T:138596942928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 85, in router
                                                options = self.before_routing_action(params=params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 725, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 900, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read(opener)
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/urllib2.py", line 429, in open
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-debug/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno 111] Connection refused>`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

The connection should not be refused

**Actual behavior:** [What actually happened]

The connection is refused (but not every time which indicates a timing issue)

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by asciidisco** [comment]
Seems like the server for the service isn't up & running,
I wanted to replace this impl. with [script.module.addon.signals](https://github.com/ruuk/script.module.addon.signals) anyway.

I hope this will solve this then as well.

**Comment by im85288** [comment]
Great, I used the signals addon in my nextup addon to signal the watched status to the Trakt Kodi addon. Isn’t it only for communication between separate addons? In the little bit of googling I did on urllib2 I read it was better to try and use requests instead.

Anyway happy to test/trial something when your ready

**Comment by asciidisco** [comment]
If you look at the `addon.xml`, the plugin actually consists of 2 plugins (so to say).
One is a service that gets started at Kodi login & brings up 2 webservers.
One webserver is needed to translate the manifest data from Netflix (the MSL format) to something Inputstream.Adaptive can understand.
The other is basically a caching proxy for requests in direction of the Netflix content API (we implemented that for performance reasons).

We use Requests to communicate with the Netflix API, but didn't want to have the memory tradeoff of using it for our internal communication. The plan is to replace the content API proxy webserver with the signals addon, to get rid of the overhead that comes with HTTP communication (and hopefully to get rid of timing bugs on startup)

**Comment by im85288** [comment]
Thanks for the explanation, that does sound like it will improve performance (I have never profiled the signals addon but would think it was faster).

An alternative solution may be just to give it a few retries if the connection is refused. I say that because if I have say 3 home widgets pointing at this addon, only the first call fails.

I could look into that approach if it helps. Thanks
