### ISSUE TITLE
Cannot get Episode list for any series

### ISSUE THREAD

**Issue by PxPert** [asciidisco/plugin.video.netflix#215]
*I'm submitting a ...*
  -  bug report

### Prerequisites

* Are you running the latest version? Yes (0.12.6), Kodi Git 19/10/2017

### Description

When I Select one Serie (for Example Stranger Things), I Can see the Season list, but when I select any season, I get an error and cannot go forward. Watching Films works

### Steps to Reproduce

1. Select a Serie
2. Select a season

**Expected behavior:** Get Episode List

**Actual behavior:** Error:

```
15:21:19.410 T:140579797489408   ERROR: Traceback (most recent call last):
15:21:19.410 T:140579797489408   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 290, in _handle_request_noblock
15:21:19.410 T:140579797489408   ERROR:     self.process_request(request, client_address)
15:21:19.410 T:140579797489408   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 318, in process_request
15:21:19.410 T:140579797489408   ERROR:     self.finish_request(request, client_address)
15:21:19.410 T:140579797489408   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
15:21:19.410 T:140579797489408   ERROR:     self.RequestHandlerClass(request, client_address, self)
15:21:19.410 T:140579797489408   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
15:21:19.410 T:140579797489408   ERROR:     self.handle()
15:21:19.410 T:140579797489408   ERROR:   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
15:21:19.410 T:140579797489408   ERROR:     self.handle_one_request()
15:21:19.410 T:140579797489408   ERROR:   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
15:21:19.410 T:140579797489408   ERROR:     method()
15:21:19.411 T:140579797489408   ERROR:   File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 60, in do_GET
15:21:19.411 T:140579797489408   ERROR:     result = getattr(RES_HANDLER, method)(params)
15:21:19.411 T:140579797489408   ERROR:   File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 215, in fetch_episodes_by_season
15:21:19.411 T:140579797489408   ERROR:     response_data=raw_episode_list)
15:21:19.411 T:140579797489408   ERROR:   File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 1357, in parse_episodes_by_season
15:21:19.411 T:140579797489408   ERROR:     genres=response_data.get('value', {}).get('genres'))
15:21:19.411 T:140579797489408   ERROR:   File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 1416, in parse_episode
15:21:19.411 T:140579797489408   ERROR:     'plot': episode['info']['synopsis'],
15:21:19.411 T:140579797489408   ERROR: KeyError: 'info'
15:21:19.419 T:140580616668928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "/home/pxpert/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 140, in router
                                                tvshowtitle=params.get('tvshowtitle'))
                                              File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 342, in show_episode_list
                                                'cache': True}))
                                              File "/home/pxpert/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 883, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read(opener)
                                              File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib64/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib64/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib64/python2.7/urllib2.py", line 1201, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib64/python2.7/httplib.py", line 1136, in getresponse
                                                response.begin()
                                              File "/usr/lib64/python2.7/httplib.py", line 453, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib64/python2.7/httplib.py", line 417, in _read_status
                                                raise BadStatusLine(line)
                                            BadStatusLine: ''
                                            -->End of Python script error report<--
15:21:19.449 T:140581736409152   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?action=episode_list&season_id=80077209&tvshowtitle=U3RyYW5nZXIgVGhpbmdz
15:21:19.451 T:140581736409152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=episode_list&season_id=80077209&tvshowtitle=U3RyYW5nZXIgVGhpbmdz) failed
```

### Installation

* I´m using the Netflix Repo

### Operating System

* Linux (x86/x64)

**Comment by asciidisco** [comment]
Seems like Netflix changed the API, will investigate over the weekend.

**Comment by pinoelefante** [comment]
i have the fix

**Comment by asciidisco** [comment]
@pinoelefante Are you going to send a PR?

**Comment by PxPert** [comment]
Hi,
I confirm this fix seems to work correctly, thanks for now!
