### ISSUE TITLE
Always get a socket.timeout when trying to browse netflix

### ISSUE THREAD

**Issue by marcbau** [asciidisco/plugin.video.netflix#254]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [YES] Are you running the latest version?

### Description

Cannot browser or view.

### Steps to Reproduce

1. Select „My list“
2. Error

**Expected behavior:** [What you expected to happen]
No error

**Actual behavior:** [What actually happened]

```
23:03:52.595 T:139786641052608   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
23:03:55.201 T:139785708480256 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
23:04:12.079 T:139784034596608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 128, in router
                                                start=start)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 425, in show_video_list
                                                'cache': True}))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 883, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read(opener)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                              File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
                                              File "/usr/lib/python2.7/httplib.py", line 438, in begin
                                              File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
                                              File "/usr/lib/python2.7/socket.py", line 480, in readline
                                            timeout: timed out
                                            -->End of Python script error report<--
23:04:12.143 T:139786641052608   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?action=video_list&type=netflixOriginals&video_list_id=34dfe14f-e42b-45b4-aaec-7515d664ab00_32271756X55XX1512931052340
23:04:12.144 T:139786641052608   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=video_list&type=netflixOriginals&video_list_id=34dfe14f-e42b-45b4-aaec-7515d664ab00_32271756X55XX1512931052340) failed
23:04:16.583 T:139784179115776   ERROR: Traceback (most recent call last):
23:04:16.583 T:139784179115776   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
23:04:16.584 T:139784179115776   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
23:04:16.584 T:139784179115776   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
23:04:16.584 T:139784179115776   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
23:04:16.584 T:139784179115776   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
23:04:16.584 T:139784179115776   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
23:04:16.584 T:139784179115776   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
23:04:16.585 T:139784179115776   ERROR: error: [Errno 32] Broken pipe

```

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreELEC 9.0 Build 1208

**Comment by marcbau** [comment]
Figured out that this is really a timeout in the addon.

Most menu items run into timeout. I guess there are too many movies behind. The only lists I was able to see is the kids list and genres > action thriller. Action krimi as example and tons of others do not work.

I cannot find a setting to increase the timeout value. My inet connection is fast. This way it is really impossible to use netflix.

**Comment by marcbau** [comment]
Enabling local library has improved the issue a bit inside Genres. All other lists are still 100% broken.

**Comment by Geczy** [comment]
Same issue, can't find a way to increase timeout

**Comment by enen92** [comment]
Same issue here. I was able to "solve it" by adding a large timeout in urllib2.urlopener method in navigation.py:

`data = urllib2.urlopen(full_url, timeout=30).read(opener)`

**Comment by asciidisco** [comment]
This can happen due to startup delays of the service. I´m tinkering with a solution to replace the http communication with one that uses an async message bus, that should eliminate the root cause of this.

**Comment by mikejrh** [comment]
same issue;  how do you increase timeout in  urllib2.urlopen (where is code located ? )

**Comment by Wailerman** [comment]
Hi !
@enen92 your solution worked pretty fine for me ! Thank you !!!

@mikejrh this is the path (at least in my libreelec running on RPI)

/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py

Tks

**Comment by chaoscommander** [comment]
Still relevant in recent version 0.13.19! This workaround helped.
