### ISSUE TITLE
[Profiles] Cant start plugin

### ISSUE THREAD

**Issue by ImmoWetzel** [asciidisco/plugin.video.netflix#258]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Just installed the plugin and insert my credentials
### Prerequisites

* [x ] Are you running the latest version?

### Description

[Description of the bug or feature]
23:37:35.012 T:1942770080   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
23:37:41.560 T:1404040080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 85, in router
                                                options = self.before_routing_action(params=params)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 708, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 883, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read(opener)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
23:37:41.602 T:1942770080   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
23:37:41.603 T:1942770080   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
23:38:35.673 T:1670521744  NOTICE: ES: Client  from ::ffff:192.168.155.53 timed out

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Geczy** [comment]
same issue

**Comment by ccope** [comment]
I noticed Netflix didn't show up as a running addon (in in System -> Add-ons -> Running) after I installed it (I was also missing pycryptomex). urlopen was failing because the service hadn't configured the port yet, so it was trying to load `http://127.0.0.1:/is_logged_in` or something like that. After installing pycryptomex, I had to restart Kodi to get the plugin to show as running. You should probably add a check that the service is alive and pop up a toast notification if not.

**Comment by asciidisco** [comment]
There will be an auto installation of missing dependencies within one of the next versions, as well as a non http based async message bus communication with proper error handling.

**Comment by asciidisco** [comment]
Full debug log please.

**Comment by asciidisco** [comment]
Closing this in favour of: https://github.com/asciidisco/plugin.video.netflix/issues/254

**Comment by ccope** [comment]
I saw the same traceback in my logs as the original post, and the Connection Refused exception is different than the socket timeout exception in #254.

Repro steps:
1. Wipe the kodi data directory
2. pip uninstall pycryptomex
3. Start kodi, install the netflix repo and plugin
4. Attempt to open the netflix plugin
5. pip install pycryptomex while kodi is still running
6. Try opening the netflix plugin again

Steps 2 + 5 may not be necessary but I won't have time to test for a few days.

**Comment by Pysis868** [comment]
`pycryptodomex`*
