### ISSUE TITLE
Title with french accent can't be exported to library

### ISSUE THREAD

**Issue by mac1202** [asciidisco/plugin.video.netflix#331]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ ] Are you running the latest version?
yes
### Description
I m using the french version of netflix when I try to export to library a title with accent (for example 13 reasons why : au delà des raisons) the plugin give me this error : 
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe0' in position 87: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 160, in router
                                                self.export_to_library(video_id=params['id'], alt_title=alt_title)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 593, in export_to_library
                                                build_url=self.build_url)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Library.py", line 371, in add_movie
                                                self.write_strm_file(path=filename, url=url, title_player=movie_meta)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Library.py", line 117, in write_strm_file
                                                self.log('Writing {}'.format(path.decode('ascii','ignore')))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 87: ordinal not in range(128)
                                            -->End of Python script error report<--
```

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by liberty-developer** [comment]
Pls. update your repo / or the netflix addon.
You should at least use 0.12.9

**Comment by mac1202** [comment]
Thank for your advice but that the version I already use.

**Comment by liberty-developer** [comment]
> File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Library.py", line 117, in write_strm_file

At line 117 / version 0.12.9 is no code which will produce this error.
So most likely you are NOT at the current version.

**Comment by hawkeyexp** [comment]
I had some probs like you with german special chats and i fixed it in last commits.
Here it is:
[https://github.com/asciidisco/plugin.video.netflix/commit/18af801fb36b88df6ade95149d91daabaf5e8d7e](url)

It was released as part of 0.12.9.
As a temp solution you can comment out the log lines self.log with a leading #

@liberty-developer have you an idea what can go wrong? The decode as ascii with ignore should be rockstable and has no probs with german special chars like ' in Marvel's Iron Fist etc.

**Comment by liberty-developer** [comment]
@mac1202 so sry, the line 117 does not make any sense but the full log shows you're on a correct version.
Can you pls. try the branch encode? Select branch, Download as zip, and install in kodi from zip file.

**Comment by mac1202** [comment]
Didnt find the encode branch so i try the latest master as I see some commit about encode. Now I cant export anything to library. I get this error.
for TV shows
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NetflixCommon' object has no attribute 'get_local_string'
                                            Traceback (most recent call last):
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 162, in router
                                                self.export_to_library(video_id=params['id'], alt_title=alt_title)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 612, in export_to_library
                                                in_background=in_background)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Library.py", line 404, in add_show
                                                progress.create(self.nx_common.get_local_string(650), show_meta)
                                            AttributeError: 'NetflixCommon' object has no attribute 'get_local_string'
                                            -->End of Python script error report<--
```

for movie. 
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NetflixCommon' object has no attribute 'get_local_string'
                                            Traceback (most recent call last):
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 162, in router
                                                self.export_to_library(video_id=params['id'], alt_title=alt_title)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 591, in export_to_library
                                                build_url=self.build_url)
                                              File "/home/mac//.kodi/addons/plugin.video.netflix/resources/lib/Library.py", line 361, in add_movie
                                                progress.create(self.nx_common.get_local_string(650), movie_meta)
                                            AttributeError: 'NetflixCommon' object has no attribute 'get_local_string'
                                            -->End of Python script error report<--
```

**Comment by mac1202** [comment]
Fixed with latest update. Thank you.
