### ISSUE TITLE
Plugin will not start and throws error

### ISSUE THREAD

**Issue by skcih** [asciidisco/plugin.video.netflix#351]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X ] support request

## General information

The plugin was working fine prior then updated to latest version of plugin and was asked to update widevinecdm. Unit downloaded chrome recovery image and installed widevinecdm and I restarted. Now unit will not play netflix videos. Tried to downgrade the netflix plugin to prior versions and have same issue now. Also uninstalled plug in and reinstalled it in which case we circle back to asking to update widevinecdm. I have been running the same version of librelec throughout this process (no changes).

I read some other posts and also tried to downgrade to older versions of the plugin and replace the widevinecdm with an older version but no such luck. Seems I can't go back in time.

Any help or recommendations are appreciated. I believe I posted the correct debug log below.

### Prerequisites

* [Yes] Are you running the latest version? Yes

**Expected behavior:** Video to play

**Actual behavior:** Playback error, check log

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ X] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Running  libreelec Leia (kodi 18)  on s905X andriod box

Debug Log

https://pastebin.com/NTapwKLd

## Other information

Prior I had an issue where the netflix library was not showing. I had to edit one file to include some brackets in order to work. I point this out if it is potentially helpful to determine what is going on here.

**Comment by skcih** [comment]
Seems only 13.2 is available in the repo. How do I go about getting a 13.4 build?

**Comment by xilopaint** [comment]
Go to [releases](https://github.com/asciidisco/plugin.video.netflix/releases) and click on `Show two newer tags`. You will see 0.13.3 and 0.13.4.

**Comment by skcih** [comment]
Updated to 13.4 and now netflix will not even open.Goes immediately to error. I updated my log with the new code. Any insight or help is appreciated.

https://pastebin.com/NTapwKLd

**Comment by mrfixit2001** [comment]
Still errors out for me with the newest plugin version. Won't even open.

15:14:09.593 T:3830420432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 98, in router
                                                options = self.before_routing_action(params=params)
                                              File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 797, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 984, in call_netflix_service
                                                parsed_json = json.loads(data, object_pairs_hook=OrderedDict)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

**Comment by skcih** [comment]
13.6 & 13.7 both work currently, thanks
