### ISSUE TITLE
Support for image-based subtitles? A (still) *buggy* workaround but it can be done..!!

### ISSUE THREAD

**Issue by Haris1977** [asciidisco/plugin.video.netflix#361]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?
Yes

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

As the title says. Some subs (like Greek/Hebrew) are image based rather than text based. Are you planning on having support for image-based subtitles?

**Comment by Haris1977** [comment]
I dont know that. Is it a kodi's issue then?

**Comment by Haris1977** [comment]
Well.. I have partially managed to see text based (greek) subs with this addon. It propably works with other subs too - it is still VERY VERY BUGGY with lack of settings - but..you may try. 

I went to this page http://www.nihongonobaka.com/download-japanese-subtitles-as-text-from-netflix-using-a-kodi-plugin/ and downloaded "netflixsubs plugin" (Kudos to the dev). Open it, download the sub file you want to see, save it to a path you have chosen in settings, then start netflix plugin and  you choose "browse for subtitle" when the movie/serie starts. In other words this plugin 'grabs' the sub you want, saves it, but then you MUST manually browse for this sub. I know it is cumbersome but..imagine those 2 plugins in one..I repeat: it has MANY MANY bugs but it is a good base for the @devs to start play with.

PS1: When you download the sub you want (with the netflixsubs plugin) kodi crashes. Just close kodi and restart. Hope this will be fixed in the future
PS2: For now, you just download one *.srt file at the time. 
PS3: Imagine those 2 plugins united as one. At the time a movie starts netflixsubs downloads the sub and then it auto browse it and plays it;)

**Comment by Sandbird** [comment]
hmm, good find, but for me its not working. I am getting this error:
```
00:01:07.522 T:1447817952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Incorrect padding
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/resources/lib/Navigation.py", line 85, in router
                                                options = self.before_routing_action(params=params)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/resources/lib/Navigation.py", line 696, in before_routing_action
                                                credentials = self.kodi_helper.get_credentials()
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/resources/lib/KodiHelper.py", line 173, in get_credentials
                                                'password': self.decode(enc=password)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflixsubs/resources/lib/KodiHelper.py", line 203, in decode
                                                enc = base64.b64decode(enc)
                                              File "/usr/lib/python2.7/base64.py", line 78, in b64decode
                                                raise TypeError(msg)
                                            TypeError: Incorrect padding
                                            -->End of Python script error report<--
00:01:07.577 T:1208451808   ERROR: GetDirectory - Error getting plugin://plugin.video.netflixsubs/
00:01:07.579 T:1918317152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflixsubs/) failed

```
but the padding in addon.py isnt wrong..I dont know why its complaining.
I've set up 'el' in the settings as well.
One thing that bothered me was that when i first ran the plugin, it wouldnt do anything..besides getting the loading icon at the bottom right corner. When i pressed ESC after 1 min, then i got the login box...and then i did exactly the same for the password. After that i was just getting the above error.

**Comment by Zarxrax** [comment]
Author of the above modded plugin here...
I just want to make it clear that I'm not doing anything to add image-sub support. My mod just takes the subtitles that are already loaded by the Netflix plugin and it redirects them to a file.
If you need assistance with it, please ask on my site ( http://www.nihongonobaka.com/download-japanese-subtitles-as-text-from-netflix-using-a-kodi-plugin/ ) because I don't check this github page. I also may not be able to answer anything quickly because I'm very busy at the moment.

**Comment by Haris1977** [comment]
I have managed to stop kodi from crashing when loading the **netflixsubs plugin**. I just downloaded the 2018-Apr-09 nightly version of kodi from here http://mirrors.kodi.tv/nightlies/windows/win64/master/ (windows version). It works fairly well with no crashing.
The strange thing is that netflixsubs plugin (which is somehow similar to plugin.video.netflix i suppose) PLAYS the video file normally and _if_ you go to subs settings you can even see that the **_greek subtitles do exist as Greek Modern 1453 file_**) but – as it is not its purpose – subtitles are not superimposed in video. So..netflixsubs plugin does SEE the subs but plugin.video.netflix no..

**Comment by Sandbird** [comment]
I wonder if anyone can do this instead: https://github.com/Andr3wHur5t/Netflix-Google-Translate
Use a .js to do a live translate with google on the good English subs that already exist.
It cant be that bad of a translation.

**Comment by mantori** [comment]
The work done in https://github.com/Zarxrax/NetflixSubs enables using subtitles as follows:
1. Use NetflixSubs and configure it to download subtitles to some directory.
2. Configure Kodi-->System-->player-->language to use the same directory as above.

When you play some Netflix title, you can manualy select subtitles from the directory and it works.

I hope that someone will merge this so that all will be done naturally and without the need for such an ugly workaround.
