### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by alorbach** [asciidisco/plugin.video.netflix#411]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Start Netflix Addon

**Expected behavior: it should login and show netflix

**Actual behavior: nothing except error 

### Installation

* [ x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

10:23:28.181 T:2540   DEBUG: [Netflix] Started (Version 0.13.10)
10:23:28.181 T:2540   DEBUG: [Netflix] "Navigation::router" called with arguments :paramstring = action=video_lists&profile_id=GF3BQUKT2VDPZDAI45M5TKDTSM:
10:23:28.182 T:2540   DEBUG: [Netflix] "Navigation::before_routing_action" called with arguments :params = {'action': 'video_lists', 'profile_id': 'GF3BQUKT2VDPZDAI45M5TKDTSM'}:
10:23:28.183 T:7320   DEBUG: [Netflix] No cookies found
10:23:28.200 T:2540   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u20ac' in position 5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 98, in router
                                                options = self.before_routing_action(params=params)
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 808, in before_routing_action
                                                self.nx_common.set_credentials(credentials['email'], credentials['password'])
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\NetflixCommon.py", line 69, in set_credentials
                                                encoded = NetflixCredentials().encode_credentials(email, password)
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\NetflixCredentials.py", line 27, in encode_credentials
                                                'password': self.encode(raw=password)
                                              File "C:\Users\mediapc\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\NetflixCredentials.py", line 65, in encode
                                                raw = bytes(Padding.pad(data_to_pad=raw, block_size=self.bs))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 5: ordinal not in range(128)
                                            -->End of Python script error report<--

## Other information

It can't encode this unicode character: \u20ac
Which is actually an € sign. I have no Idea from where it is comming.

**Comment by liberty-developer** [comment]
pls. deinstall netflix addon (including user-data), and install from zip again.

**Comment by liberty-developer** [comment]
Yes, understand your suggestion, thanx for reporting back!
