### ISSUE TITLE
Exception after login

### ISSUE THREAD

**Issue by ChasakisD** [asciidisco/plugin.video.netflix#444]
*I'm submitting a ...*
  - [/] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [/] Are you running the latest version?

### Description

When netflix app launches, after the login, it throws this exception and nothing seems to work
```
16:18:04.812 T:15788   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.UnicodeDecodeError'>
    Error Contents: 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)
    Traceback (most recent call last):
        File "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 33, in <module>
        NAVIGATION.router(paramstring=REQUEST_PARAMS)
        File "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 45, in wrapped
        result = func(*args, **kwargs)
        File "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 123, in router
        return self.show_profiles()
        File "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 45, in wrapped
        result = func(*args, **kwargs)
        File "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 522, in show_profiles
        build_url=self.build_url)
        File "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\KodiHelper.py", line 230, in build_profiles_listing
        unescaped_profile_name = html_parser.unescape(enc_profile_name)
        File "C:\Program Files\Kodi\system\python\Lib\HTMLParser.py", line 475, in unescape
        return re.sub(r"&(#?[xX]?(?:[0-9a-fA-F]+|\w{1,8}));", replaceEntities, s)
        File "C:\Program Files\Kodi\system\python\Lib\re.py", line 155, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)
    -->End of Python script error report<--
16:18:04.840 T:15788 WARNING: CPythonInvoker(12, C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): the python script "C:\Users\**username**\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
16:18:04.841 T:13096   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.netflix/
16:18:04.850 T:4548   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
```

### Steps to Reproduce

1. Clean Install of 0.13.10
2. Open the app and login

**Expected behavior:** 
The app should open

**Actual behavior:**
An exception is thrown and cannot continue

## Context (Environment)
KodiSetup-20180816-5f77b6d5-master-x64.exe

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [/] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [/] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Windows 10 Pro 64bit Version 1803 Build 17134.228

## Debug log

[kodi](https://pastebin.com/ceb742m0)

**Comment by caphm** [comment]
You have characters in one of your profile names that are non-ascii. Change your profile names to only contain ascii-compatible characters and it will work.
