### ISSUE TITLE
Access Netflix extern

### ISSUE THREAD

**Issue by Animizio** [asciidisco/plugin.video.netflix#454]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

### Prerequisites

* [x ] Are you running the latest version?

### Description

[Description of the bug or feature]

Accessing the Netflix Addon extern with an multisearch addon.
Searching in my Addon and playing through your Addon.

**Expected behavior:** [What you expected to happen]

I would like to access this addon extern for a search addon.
Thats enough?

plugin://plugin.video.netflix/?action=play_video&video_id=70099789

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ x] Any

**Comment by Philps** [comment]
similar to this request: https://github.com/Sandmann79/xbmc/issues/128

**Comment by caphm** [comment]
Thanks for the hint @Philps!

@Animizio: If you already know the Netflix video id then yes, the call you listed will be enough.

Is there any place I can have a look at your plugin and test it out? I was thinking of implementing something similar someday as well.

**Comment by Philps** [comment]
@caphm: thats something to look into. does netflix has a similar api as amazon? how are search queries being made, so that a netflix video id is being returned?

alternatively ( as a workaround ) justwatch.com could be used but its less preffered.
 https://www.justwatch.com/us/search?q=kill%20bill&providers=nfx

any help would be appreciated

**Comment by caphm** [comment]
There is currently no way to programmatically query the search.

Do you want to auto-play the first returned result or display a selection of results and let the user choose which one to play? The former may be tricky, as even an exact match is not always returned as the first result by Netflix.

**Comment by Philps** [comment]
get a list of search results and compare against the search title to get a match. 
how this Addon is doing the search?

**Comment by Philps** [comment]
So movie part is working, however i am having issues ( probably due to encoding of the params?) for tv shows

Neither is working:

plugin://plugin.video.netflix/?action=play_video&video_id=70242311%26infoLabels%3D%7B%27episode%27%3A5%2C%27season%27%3A6%7D

plugin://plugin.video.netflix/?action=play_video&video_id=70242311&infoLabels={'episode':5,'season':6}


DEBUG: [Netflix] "Navigation::router" called with arguments :paramstring = action=play_video&video_id=70242311&infoLabels={'episode':5,'season':6}:

DEBUG: [Netflix] "Navigation::before_routing_action" called with arguments :params = {'action': 'play_video', 'infoLabels': "{'episode':5,'season':6}", 'video_id': '70242311'}:

DEBUG: [Netflix] "Navigation::play_video" called with arguments :infoLabels = {'episode':5,'season':6}::video_id = 70242311::start_offset = -1:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'creditMarkers'
                                            Traceback (most recent call last):
                                              File "\Kodi\addons\plugin.video.netflix\addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 253, in router
                                                infoLabels=params.get('infoLabels', {}))
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 306, in play_video
                                                timeline_markers=self._get_timeline_markers(video_id))
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 316, in _get_timeline_markers
                                                markers.update(_get_section_markers(metadata))
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 49, in _get_section_markers
                                                for section in SKIPPABLE_SECTIONS
                                              File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 50, in <dictcomp>
                                                if (None not in metadata['creditMarkers'][section].values() and
                                            KeyError: 'creditMarkers'
                                            -->End of Python script error report<--

**Comment by Philps** [comment]
ok. the issues with episode is as follow: 
 the episode requires a netflix ID instead of numeric sheme. 

where do i find the episodeID for a TV SHow?

**Comment by Philps** [comment]
This issue can be closed

# Search MovieID or TvShowID using a search engine and extract the ID
# For Video

plugin://plugin.video.netflix/?action=play_video&video_id=<MovieID>

#For TvShow Episodes

plugin://plugin.video.netflix/?action=play_video&video_id=<EpisodeID>&infoLabels=season=<seasono.>&episode=<episodeno.>&mediatype=episode

Note: pass on Info Labels as params eg. infoLabels=urllib.urlencode({'episode':episode,'season':season,'mediatype':'episode'})
