### ISSUE TITLE
KeyError: 'creditMarkers'  in Navigation.py when external call to tvshows

### ISSUE THREAD

**Issue by Philps** [asciidisco/plugin.video.netflix#460]
*I'm submitting a ...*
  - [x ] bug report

## General infomration

if (None not in metadata['creditMarkers'][section].values() and KeyError: 'creditMarkers'

## Context (Environment)

Win7 32bit

### Installation

* [x ] I´m using the Netflix Repo

### Operating System

* [ ] Windows (x86/x64)

## Debug log

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: 'creditMarkers'
Traceback (most recent call last):
File "\Kodi\addons\plugin.video.netflix\addon.py", line 33, in 
NAVIGATION.router(paramstring=REQUEST_PARAMS)
File "\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
result = func(*args, **kwargs)
File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 253, in router
infoLabels=params.get('infoLabels', {}))
File "\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
result = func(*args, **kwargs)
File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 306, in play_video
timeline_markers=self._get_timeline_markers(video_id))
File "\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
result = func(*args, **kwargs)
File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 316, in _get_timeline_markers
markers.update(_get_section_markers(metadata))
File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 49, in _get_section_markers
for section in SKIPPABLE_SECTIONS
File "\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 50, in 
if (None not in metadata['creditMarkers'][section].values() and
KeyError: 'creditMarkers'
-->End of Python script error report<--

## Other information

See: https://github.com/asciidisco/plugin.video.netflix/issues/454#issuecomment-417247373

**Comment by Philps** [comment]
the problem seem to be that the eposide_id get the value of the video_id


def _get_single_metadata(self, video_id):
       ....        
        return (find_episode(video_id, metadata['seasons'])
                if metadata['type'] == 'show'
                else metadata)


def find_episode(episode_id, seasons):
    for season in seasons:
        for episode in season['episodes']:
            if str(episode['id']) == episode_id:
                print "print NFA find_episode utils.py episode",episode  <--- this somehow matches the video_id ??

                return episode
    return {}

**Comment by Philps** [comment]
problem is with def find_episode(episode_id, seasons):

the external pluginin uses the episodeif BUT Netflix uses the VideoID

Any chance to adjust this? or what would be the workaround to match the EpisodeID

**Comment by Philps** [comment]
issue is due to incorrect usage of episode. the episode requires a netflix ID instead of numeric sheme

**Comment by Philps** [comment]
video_id is a unique id for Video(Film) and Episodes. Probably its not requried to send infos such as "Season 1", Episode 2.

However its not clear where to recieve the Episode ID from
