### ISSUE TITLE
Can't open plugin/login - Error Type: <class 'urllib2.URLError'> Error Contents: <urlopen error [Errno 10061] 

### ISSUE THREAD

**Issue by Stueck** [asciidisco/plugin.video.netflix#479]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General infomration
Installed:
Kodi 18 Beta 2
Amazon Prime Addon
Netflix Addon
Connection gets refused
Problems with python connection?

### Prerequisites

* [x] Are you running the latest version?

### Description

Can't open Addon - fails with error. I am not able to insert login data

### Steps to Reproduce

1. Open Plugin
or open user data setup

**Expected behavior:** 
Netflix Login and opening plugin possible

**Actual behavior:** 
error

## Context (Environment)
Windows 10 x64
Kodi 18 Beta 2 x86
newest Netflix Plugin from Repo

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Simply Windows 10 x64 with installed Kodi as .exe

## Debug log

https://pastebin.com/zFvNfEjr

## Other information
Relevant Error:
 Error Type: <type 'exceptions.ImportError'>
Error Contents: No module named Cryptodome.Random
and

Error Type: <class 'urllib2.URLError'>
Error Contents: <urlopen error [Errno 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte>

Also installed manual a python 3.7 for windows and did pip install cryptodome and cryptodomex. But I don't know if it works like this on windows

**Comment by Stueck** [comment]
I was able to fix it  by coping
c:\program files (x86)\Kodi\addons\script-module.pycrptodome\lib\Cryptodome
to
c:\program files (x86)\Kodi\system\Python\Lib\site-packages\Cryptodome
and to
c:\program files (x86)\Kodi\system\Python\Lib\site-packages\Crypto

But this shouldn't be the solution, or?


But now I have a new problem.
I updated already my intel graphics driver because kodi crashed on playback. So this works now.
But not every movie starts... when I put in InputStream Adaptive the max resolutions at 720p then it starts. Isn't it possible to see in 1080p with windows and a kaby lake?

**Comment by caphm** [comment]
No, it should not be. The cryptodome module usually comes in the Python\Lib\site-packages\Cryptodome with a fresh installation of Kodi 18 on Windows. Did you do an in-place upgrade from Krypton?

I don't quite understand your other issues:

1. What exactly happens when you try to play a video in 1080p? Does it play in a lower quality? Does it start but show a black screen (with audio maybe)? Is it stuck on the loading animation? Does anything happen at all?
For some content the max resolution is restricted by Netflix, because Windows always identifies as Chrome and is thus Widevine L3. For these devices content may only be available in a lower quality than on other (L1) systems.
2. Regarding audio: Does it simply not play any sound at all when you select the stream? (while continuing to play video)

Regarding video and audio issues, a debug log would be helpful.

**Comment by Stueck** [comment]
Yes, I did an in-place upgrade from the last Krypton release. 

Okay, sorry for my bad explanation.

1. It shows the loading circle and after a few seconds it disappears and I see simply the the netflix list.
When I select in InputStream Adaptive max resolutions 720p the movie starts. As I see netflix doesn't support 1080p via Chrome. But in my view of this case the movie should simply load in 720p, or?

2. It doesn't play the german DD+ 6 Speaker audio. When I switch to DD+ 2 speaker german audio it works. Also when I switch to DD+ 6 speaker english audio (or italian or spanish) it works. Only the pre selected audio doesn't work.

Here I have a debug log for 1080p video issue (movie doesn't start):
https://pastebin.com/3cm8CnYF
Here the debug log for the audio issue:
https://pastebin.com/giE2Teca

Thank you very much for your help

**Comment by Stueck** [comment]
After updating to Beta 3 there is again no connection to netflix possible.
had again to copy CryptoDome to c:\program files (x86)\Kodi\system\Python\Lib\site-packages\Crypto

My other problems persist

**Comment by caphm** [comment]
Sorry, I didn't have any time investigating your issues. The links to the logs have expired, could you upload them again and increase the expiration time please? I can't tell right now when I will be able to look into this.

**Comment by Stueck** [comment]
Of course, no problem. Here again:

debug log for 1080p video issue (movie doesn't start):
https://pastebin.com/YrphfABe
debug log for the audio issue:
https://pastebin.com/EgjiA6FC

**Comment by caphm** [comment]
The video doesn't start because inputstream can't download the video data (404 Not Found):

> 16:07:58.794 T:3192   DEBUG: AddOnLog: InputStream Adaptive: OpenStream(1)
> 16:07:58.795 T:3192   DEBUG: AddOnLog: InputStream Adaptive: Selecting stream with conditions: w: 1920, h: 1080, bw: 9375355
> 16:07:58.795 T:3192   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=0-62912'
> 16:07:58.795 T:3192   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
> 16:07:58.795 T:3192   DEBUG: CurlFile::Open(0x19086838) http://89.27.129.82/?o=AQFNhvc-RoyNAboKlt3bbp7_uObtb1-kJOqQj_gvOZeEXwp6tyCQuHt1qFQ_MekR81TxKTA6Xl2HFXUfKWp61j-kyzh_PqNldf5sGbNHTLLJtn-p8BjYs-wwiszsVEVG59dN-g1sJvd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=Up_FRPZiyxGLQkNtI7lLL5umSzY
> 16:07:58.795 T:3192    INFO: XCURL::DllLibCurlGlobal::easy_acquire - Created session to http://89.27.129.82
> 16:07:58.857 T:3192   ERROR: AddOnLog: InputStream Adaptive: Download http://89.27.129.82/?o=AQFNhvc-RoyNAboKlt3bbp7_uObtb1-kJOqQj_gvOZeEXwp6tyCQuHt1qFQ_MekR81TxKTA6Xl2HFXUfKWp61j-kyzh_PqNldf5sGbNHTLLJtn-p8BjYs-wwiszsVEVG59dN-g1sJvd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=Up_FRPZiyxGLQkNtI7lLL5umSzY failed with error: 404
> 16:07:58.857 T:3192   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 16:07:58.857 T:6780   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=0-62912'
> 16:07:58.857 T:6780   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
> 16:07:58.857 T:6780   DEBUG: CurlFile::Open(0x19086838) http://89.27.129.82/?o=AQFNhvc-RoyNAboKlt3bbp7_uObtb1-kJOqQj_gvOZeEXwp6tyCQuHt1qFQ_MekR81TxKTA6Xl2HFXUfKWp61j-kyzh_PqNldf5sGbNHTLLJtn-p8BjYs-wwiszsVEVG59dN-g1sJvd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=Up_FRPZiyxGLQkNtI7lLL5umSzY
> 16:07:58.917 T:6780   ERROR: AddOnLog: InputStream Adaptive: Download http://89.27.129.82/?o=AQFNhvc-RoyNAboKlt3bbp7_uObtb1-kJOqQj_gvOZeEXwp6tyCQuHt1qFQ_MekR81TxKTA6Xl2HFXUfKWp61j-kyzh_PqNldf5sGbNHTLLJtn-p8BjYs-wwiszsVEVG59dN-g1sJvd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=Up_FRPZiyxGLQkNtI7lLL5umSzY failed with error: 404
> 16:07:58.918 T:3192 WARNING: CVideoPlayer::OpenStream - Unsupported stream 1. Stream disabled.

Could you try playing the movie again and grab the manifest.json and manifest.mpd files from `userdata/addon_data/plugin.video.netflix` inside your Kodi profile directory? I don't know if these URLs are provided in the manifest and the conversion to mpd somehow mangles them or if this is actually an inputstream issue.
Also, the 1080p stream is requested from a different server than the 720p one (from your other logfile):
**1080p:** `89.27.129.82`
**720p:** `ipv6_1.lagg0.c001.ham001.versatel.isp.nflxvideo.net`
This could just as well be a misconfiguration with a regional CDN server, which is not apparent in regular Netflix clients as they can dynamically switch the resolution... The server seems to be located in my area, so I'll try to reproduce when I'm at home.

This issue seems to also be the reason for your audio problems:

> 16:09:48.755 T:15484  NOTICE: Opening stream: 3 source: 256
> 16:09:48.755 T:15484   DEBUG: AddOnLog: InputStream Adaptive: OpenStream(3)
> 16:09:48.755 T:11356   DEBUG: Thread VideoPlayerVideo start, auto delete: false
> 16:09:48.755 T:11356  NOTICE: running thread: video_thread
> 16:09:48.755 T:15484   DEBUG: AddOnLog: InputStream Adaptive: Selecting stream with conditions: w: 0, h: 0, bw: 1041706
> 16:09:48.756 T:15484   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=0-62912'
> 16:09:48.756 T:15484   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
> 16:09:48.756 T:15484   DEBUG: CurlFile::Open(0x16796050) http://89.27.129.82/?o=AQFNhvc-RoyNAboKndLTaJn_veP1KEW6P7TM0aEuet_XWgp6vjfS4SV3rV07LfFapRn6MU4idFmPVgkcMkdbyy6J2xxsRN5HXYgYB9cAVK__pEek5Arasd0Du6S9R2Y5pMAC8wphJPd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=GwJB79JMm2Z0-yS6x2cVO074YxA
> 16:09:48.756 T:15484    INFO: XCURL::DllLibCurlGlobal::easy_acquire - Created session to http://89.27.129.82
> 16:09:48.829 T:15484   ERROR: AddOnLog: InputStream Adaptive: Download http://89.27.129.82/?o=AQFNhvc-RoyNAboKndLTaJn_veP1KEW6P7TM0aEuet_XWgp6vjfS4SV3rV07LfFapRn6MU4idFmPVgkcMkdbyy6J2xxsRN5HXYgYB9cAVK__pEek5Arasd0Du6S9R2Y5pMAC8wphJPd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=GwJB79JMm2Z0-yS6x2cVO074YxA failed with error: 404
> 16:09:48.829 T:15484   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 16:09:48.830 T:9684   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=0-62912'
> 16:09:48.830 T:9684   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
> 16:09:48.830 T:9684   DEBUG: CurlFile::Open(0x167962b8) http://89.27.129.82/?o=AQFNhvc-RoyNAboKndLTaJn_veP1KEW6P7TM0aEuet_XWgp6vjfS4SV3rV07LfFapRn6MU4idFmPVgkcMkdbyy6J2xxsRN5HXYgYB9cAVK__pEek5Arasd0Du6S9R2Y5pMAC8wphJPd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=GwJB79JMm2Z0-yS6x2cVO074YxA
> 16:09:48.900 T:9684   ERROR: AddOnLog: InputStream Adaptive: Download http://89.27.129.82/?o=AQFNhvc-RoyNAboKndLTaJn_veP1KEW6P7TM0aEuet_XWgp6vjfS4SV3rV07LfFapRn6MU4idFmPVgkcMkdbyy6J2xxsRN5HXYgYB9cAVK__pEek5Arasd0Du6S9R2Y5pMAC8wphJPd3ib0qPTDm_TDBa3QZtQzgIjPdw63Oz577KNzZ8IXS-5ZJWfrA3A3Q9LRzTnY_SAM0-Va5BysYkLaTVmgPEnl5Vo6b0ts_XhV4SxsLOE4&v=3&e=1537581521&t=GwJB79JMm2Z0-yS6x2cVO074YxA failed with error: 404
> 16:09:48.900 T:15484  NOTICE: Finding audio codec for: 86056
> 16:09:48.900 T:15484  NOTICE: Creating audio thread
> 16:09:48.901 T:15484  NOTICE: Opening stream: 6 source: 256
> 16:09:48.901 T:15484   DEBUG: AddOnLog: InputStream Adaptive: OpenStream(6)
> 16:09:48.901 T:4040   DEBUG: Thread VideoPlayerAudio start, auto delete: false
> 16:09:48.901 T:4040  NOTICE: running thread: CVideoPlayerAudio::Process()
> 16:09:48.901 T:15484   DEBUG: AddOnLog: InputStream Adaptive: Selecting stream with conditions: w: 0, h: 0, bw: 1041706
> 16:09:48.901 T:15484   DEBUG: CFileCache::Open - opening <> using cache
> 16:09:48.901 T:15484   DEBUG: CurlFile::Open(0x16797f98) http://ipv6_1.cc0.c062.dus002.ix.nflxvideo.net/?o=AQFNhvc-RoyNAboKltfUb536uOD2KEivKqXM0aEuet_XWgp6vjfS4SV3rV07LfFapRn6MU4idFmPVgkcMkdbyy6J2xxsRN5HXYgYB9cAVK__pEek5Arasd0Du6S9R2Y5pMAC8wt-f-xX9bE8DSOr9mDPQHsPzWyURT__14vzv4qpZoXQ5Yfa9IhBUb-WwBTW6ec2VTN6TBMw60GzWTJEgbyvDABPFjpsAt7A1IBpQQ4wRxoD&v=3&e=1537581521&t=7-FPWgXg1bJBjfmKeLw4rbDfzvU

Streams no. 2 to 5 are the DD+6 streams, no 6 to 8 the DD+2 ones:

> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 2 with codec_id 86056
> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 3 with codec_id 86056
> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 4 with codec_id 86056
> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 5 with codec_id 86056
> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 6 with codec_id 96264
> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 7 with codec_id 96264
> 16:09:48.281 T:15484   DEBUG: CDVDDemuxClient::RequestStream(): added/updated stream 8 with codec_id 96264

It tries to load stream no. 3 (GER, DD+6) but fails for the same reason your 1080p stream won't start  (404 Not Found). But since there are multiple audio streams, it switches to the next one (no. 6, GER DD+2) without any trouble.

I don't know a solution yet, the above is very detailed so the error is properly described. I'll keep on it.

Do these problems only occur with the movie Transcendence or are there other titles where this happens?

**Comment by Stueck** [comment]
Hi, I still have the problem with Cryptodome.
I just updated to Kodi 18.3. So all librarys got deleted.

Get this message when opening the netflix addon:

`2019-07-27 19:22:11.388 T:13320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome.Random
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\service.py", line 23, in <module>
                                                import resources.lib.services as services
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\__init__.py", line 6, in <module>
                                                from .msl.http_server import MSLTCPServer
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\msl\http_server.py", line 17, in <module>
                                                from .msl_handler import MSLHandler
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\msl\msl_handler.py", line 21, in <module>
                                                from .request_builder import MSLRequestBuilder
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\msl\request_builder.py", line 22, in <module>
                                                from .default_crypto import DefaultMSLCrypto as MSLCrypto
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\msl\default_crypto.py", line 7, in <module>
                                                from Cryptodome.Random import get_random_bytes
                                            ImportError: No module named Cryptodome.Random
                                            -->End of Python script error report<--
2019-07-27 19:22:11.388 T:13320   DEBUG: CPythonInvoker::onExecutionDone(4, C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.netflix\service.py)`

Will be there a fix?
Seems that it couldn't find the cryptodome within standard path.

I already tried your release from https://github.com/asciidisco/plugin.video.netflix/pull/519
