### ISSUE TITLE
Kodi don't exit correctly because several classes are left in memory.

### ISSUE THREAD

**Issue by carlosricardocm** [asciidisco/plugin.video.netflix#486]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information

I'm running kodi 18 in raspbian strech in a raspberry pi b 3

### Prerequisites

* [X] Are you running the latest version?
0.13.13

### Description

[Description of the bug or feature]

Kodi don't exit correctly because several classes are left in memory.

### Steps to Reproduce

1. [First Step]
Install the plugin version 0.13.13
2. [Second Step]
Exit Kodi

**Expected behavior:** [What you expected to happen]
Exit kodi to terminal

**Actual behavior:** [What actually happened]
Black screen or text with legend "Exiting Kodi"

## Context (Environment)
I was able to compile and install kodi 18 in raspbian stretch with some binary addon extras (inputstream and rtmp), in order to run the latest version of kodi from Emulationstation (Retropie 4.4)

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I installed Retropie 4.4 which is based on Raspbian Stretch and compile Kodi 18 with the binary extra addons instead of the Kodi 17.3 available in this distribution.

## Debug log

00:56:54.373 T:1595925232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 123, in router
                                                options = self.before_routing_action(params=params)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 867, in before
_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_
netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
00:56:54.522 T:1595925232 WARNING: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/pi/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
00:56:54.526 T:1625289456   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
00:56:54.553 T:1902452736   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
00:57:45.039 T:1578099440 WARNING: CPythonInvoker(4, /home/pi/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/pi/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

**Comment by codeHorse87** [comment]
I have the exact same issue in Linux (x86/x64) using Ubuntu

**Comment by metzenseifner** [comment]
Same issue on Linux pi-kamera 4.14.92-1-ARCH #1 SMP Thu Jan 10 04:52:45 UTC 2019 armv7l GNU/Linux

**Comment by adhossain** [comment]
My netflix doesn't open and gives the same error
