### ISSUE TITLE
Android Box 5.0 no video playback

### ISSUE THREAD

**Issue by timewolf** [asciidisco/plugin.video.netflix#498]
*I'm submitting a ...*
  - [ ] bug report 
  

## General infomration

On an old huawei box 5.0 i cannot playback any netflix video

### Prerequisites

Android Lollipop 5.0
Kodi 18 beta2 (beta 3 crash on that box)

### Description

No video playback

### Operating System

* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

15:55:12.245 T:18446744072045174912  NOTICE: ADDON: skin.estuary v2.0.12 installed
15:55:13.231 T:18446744072386573056 WARNING: CGUIMediaWindow::OnMessage - updating in progress
15:55:25.583 T:18446744072187621248   ERROR: GetDirectory - Error getting
15:56:06.310 T:18446744072386573056   ERROR: Previous line repeats 6 times.
15:56:06.310 T:18446744072386573056  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27season%27%3A+None%2C+%27tvshowtitle%27%3A+%27%27%2C+%27mediatype%27%3A+%27movie%27%2C+%27director%27%3A+u%27James+DeMonaco%27%2C+%27duration%27%3A+6548%2C+%27year%27%3A+2016%2C+%27genre%27%3A+u%22Thriller+d%27azione%22%2C+%27plot%27%3A+u%27Invoca+che+il+caos+possa+terminare%2C+ma+per+vedere+un+futuro+senza+terrore%2C+dovr%5Cxe0+superare+la+notte.%27%2C+%27episode%27%3A+%27%27%2C+%27title%27%3A+u%27La+Notte+del+giudizio%3A+Election+Year%27%2C+%27mpaa%27%3A+%27MiBAC-VM14%27%2C+%27writer%27%3A+%27%27%2C+%27cast%27%3A+%5Bu%27Elizabeth+Mitchell%27%2C+u%27Mykelti+Williamson%27%2C+u%27Frank+Grillo%27%2C+u%27Edwin+Hodge%27%2C+u%27Betty+Gabriel%27%2C+u%27Joseph+Julian+Soria%27%2C+u%27Kyle+Secor%27%2C+u%27Terry+Serpico%27%5D%7D&video_id=80094662&pin=True
15:56:06.313 T:18446744071938137088  NOTICE: Creating InputStream
15:56:06.539 T:18446744071938137088   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
15:56:07.659 T:18446744071939800064   ERROR: Traceback (most recent call last):
15:56:07.659 T:18446744071939800064   ERROR:   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
15:56:07.661 T:18446744071939800064   ERROR:   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 318, in process_request
15:56:07.662 T:18446744071939800064   ERROR:   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 331, in finish_request
15:56:07.664 T:18446744071939800064   ERROR:   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 652, in __init__
15:56:07.666 T:18446744071939800064   ERROR:   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/BaseHTTPServer.py", line 340, in handle
15:56:07.667 T:18446744071939800064   ERROR:   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
15:56:07.668 T:18446744071939800064   ERROR:   File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 67, in do_GET
15:56:07.673 T:18446744071939800064   ERROR:     dolby, hevc, hdr, dolbyvision)
15:56:07.674 T:18446744071939800064   ERROR:   File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 186, in load_manifest
15:56:07.681 T:18446744071939800064   ERROR:     request_data = self.__generate_msl_request_data(manifest_request_data)
15:56:07.681 T:18446744071939800064   ERROR:   File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 490, in __generate_msl_request_data
15:56:07.682 T:18446744071939800064   ERROR:     plaintext=self.__generate_msl_header())
15:56:07.683 T:18446744071939800064   ERROR:   File "/mnt/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 583, in __encrypt
15:56:07.685 T:18446744071939800064   ERROR:     return json.dumps(self.crypto.encrypt(plaintext, self.nx_common.get_esn(), self.sequence_number))
15:56:07.685 T:18446744071939800064   ERROR: AttributeError: 'MSL' object has no attribute 'sequence_number'
15:56:07.687 T:18446744071938137088   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
15:56:07.687 T:18446744071938137088   ERROR: CCurlFile::Open failed with code 0 for http://localhost:55150/manifest?id=80094662&dolby=true&hevc=false&hdr=false&dolbyvision=false:
15:56:07.688 T:18446744071938137088   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:55150/manifest?id=80094662&dolby=true&hevc=false&hdr=false&dolbyvision=false
15:56:07.689 T:18446744071938137088   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:55150/manifest?id=80094662&dolby=true&hevc=false&hdr=false&dolbyvision=false)
15:56:07.700 T:18446744071938137088   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27season%27%3A+None%2C+%27tvshowtitle%27%3A+%27%27%2C+%27mediatype%27%3A+%27movie%27%2C+%27director%27%3A+u%27James+DeMonaco%27%2C+%27duration%27%3A+6548%2C+%27year%27%3A+2016%2C+%27genre%27%3A+u%22Thriller+d%27azione%22%2C+%27plot%27%3A+u%27Invoca+che+il+caos+possa+terminare%2C+ma+per+vedere+un+futuro+senza+terrore%2C+dovr%5Cxe0+superare+la+notte.%27%2C+%27episode%27%3A+%27%27%2C+%27title%27%3A+u%27La+Notte+del+giudizio%3A+Election+Year%27%2C+%27mpaa%27%3A+%27MiBAC-VM14%27%2C+%27writer%27%3A+%27%27%2C+%27cast%27%3A+%5Bu%27Elizabeth+Mitchell%27%2C+u%27Mykelti+Williamson%27%2C+u%27Frank+Grillo%27%2C+u%27Edwin+Hodge%27%2C+u%27Betty+Gabriel%27%2C+u%27Joseph+Julian+Soria%27%2C+u%27Kyle+Secor%27%2C+u%27Terry+Serpico%27%5D%7D&video_id=80094662&pin=True]
15:56:07.701 T:18446744071938137088  NOTICE: CVideoPlayer::OnExit()
15:56:21.019 T:18446744072378998912  NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
15:56:21.028 T:18446744072378998912  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 120416 m_frames: 7526 m_frameSize: 8 channels: 2
15:56:30.139 T:18446744072386573056  NOTICE: stop player
15:56:30.178 T:18446744072386573056  NOTICE: CVideoPlayer::CloseFile()
15:56:30.178 T:18446744072386573056  NOTICE: VideoPlayer: waiting for threads to exit
15:56:30.179 T:18446744072386573056  NOTICE: VideoPlayer: finished waiting
15:56:30.179 T:18446744072386573056  NOTICE: CVideoPlayer::CloseFile()
15:56:30.179 T:18446744072386573056  NOTICE: VideoPlayer: waiting for threads to exit
15:56:30.179 T:18446744072386573056  NOTICE: VideoPlayer: finished waiting

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by xCreez** [comment]
Having the exact same issue on atvXperience (Android TV 7)
When selecting a video it just loads a bit and then it stops, giving the same errors as provided above

**Comment by caphm** [comment]
Fixed in current PR for 0.14.0: #519 
Keeping this open until the PR gets merged.

**Comment by ians325** [comment]
Make sure the HEVC are on for android
