### ISSUE TITLE
Unable to play some TV titles (others play OK)

### ISSUE THREAD

**Issue by ASHJG** [asciidisco/plugin.video.netflix#518]
*I'm submitting a ...*
  - [*] bug report
  - [ ] feature request
  - [ ] support request

## General information
Netflix addon cant play some tv tittle for example "Victorious", other titles seem to play ok. i have test using native android app using same profile and the tittle works ok
### Prerequisites

* [*] Are you running the latest version?

### Description

```
10:40:22.575 T:14348   DEBUG: CPythonInvoker(14, C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): start processing
10:40:22.575 T:14348   DEBUG: CPythonInvoker(14, C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): entering source directory C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix
10:40:22.576 T:14348   DEBUG: CPythonInvoker(14, C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): instantiating addon using automatically obtained id of "plugin.video.netflix" dependent on version 2.25.0 of the xbmc.python api
10:40:22.577 T:14348   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
10:40:22.577 T:14348   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
10:40:22.579 T:14348   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
10:40:22.579 T:14348   DEBUG: CSettingsManager: requested setting (logging) was not found.
10:40:22.580 T:14348   DEBUG: [Netflix] Started (Version 0.13.15)
10:40:22.580 T:14348   DEBUG: [Netflix] "Navigation::router" called with arguments :paramstring = action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+6%2C+%27plot%27%3A+u%27After+a+jealous+Jade+dumps+Beck%2C+she+soon+regrets+it+and+recruits+Tori+to+help+get+him+back.+Meanwhile%2C+Trina+puts+on+a+one-woman+show.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Victorious%27%2C+%27title%27%3A+u%27Jade+Dumps+Beck%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27Kids%5Cu2019+Programmes%27%2C+%27year%27%3A+2010%2C+%27duration%27%3A+1418%7D&video_id=70278610&pin=False&start_offset=1417:
10:40:22.581 T:14348   DEBUG: [Netflix] "Navigation::before_routing_action" called with arguments :params = {'action': 'play_video', 'infoLabels': "{'rating': 0, 'writer': '', 'episode': 6, 'plot': u'After a jealous Jade dumps Beck, she soon regrets it and recruits Tori to help get him back. Meanwhile, Trina puts on a one-woman show.', 'season': 1, 'tvshowtitle': u'Victorious', 'title': u'Jade Dumps Beck', 'mediatype': u'episode', 'mpaa': u'-', 'director': '', 'genre': u'Kids\\u2019 Programmes', 'year': 2010, 'duration': 1418}", 'start_offset': '1417', 'pin': 'False', 'video_id': '70278610'}:
10:40:22.582 T:18376   DEBUG: [Netflix] Loading cookies from memory
10:40:22.582 T:18376   DEBUG: [Netflix] Cookie expires: 1567593609 / 1541328022
10:40:22.591 T:14348   DEBUG: [Netflix] "Navigation::before_routing_action" returned: {}
10:40:22.591 T:14348   DEBUG: [Netflix] "Navigation::play_video" called with arguments :infoLabels = {'rating': 0, 'writer': '', 'episode': 6, 'plot': u'After a jealous Jade dumps Beck, she soon regrets it and recruits Tori to help get him back. Meanwhile, Trina puts on a one-woman show.', 'season': 1, 'tvshowtitle': u'Victorious', 'title': u'Jade Dumps Beck', 'mediatype': u'episode', 'mpaa': u'-', 'director': '', 'genre': u'Kids\u2019 Programmes', 'year': 2010, 'duration': 1418}::video_id = 70278610::start_offset = 1417:
10:40:22.591 T:14348   DEBUG: [Netflix] "Navigation::_get_single_metadata" called
10:40:22.596 T:8964   DEBUG: Thread scriptobs start, auto delete: false
10:40:22.633 T:15520   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
10:40:22.633 T:15520   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
10:40:22.686 T:6968   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"episode":6,"season":1,"showtitle":"Victorious","title":"Jade Dumps Beck","type":"episode"},"playlistid":1,"position":0}
10:40:22.698 T:4040   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"episode":6,"season":1,"showtitle":"Victorious","title":"Jade Dumps Beck","type":"episode"},"playlistid":1,"position":0}
10:40:22.705 T:18376   DEBUG: [Netflix] [GET] Req. for "https://www.netflix.com/api/shakti/vc2328289/metadata" took 0.111999988556 sec
10:40:22.736 T:14348   DEBUG: [Netflix] "Navigation::_get_single_metadata" returned: (OrderedDict([(u'progressImageRoot', u'https://tp-s.nflximg.net/tpa2/735/984146735/'), (u'requiresPin', False), (u'autoplayable', True), (u'end', 1569798000000L), (u'seq', 6), (u'title', u'Jade Dumps Beck'), (u'bookmark', OrderedDict([(u'watchedDate', 1541324160989L), (u'offset', 1417)])), (u'creditMarkers', OrderedDict([(u'recap', OrderedDict([(u'start', 0), (u'end', 0)])), (u'credit', OrderedDict([(u'start', 137221), (u'end', 195683)]))])), (u'creditsOffset', 1407), (u'requiresAdultVerification', False), (u'episodeId', 70278610), (u'watchedToEndOffset', 1336), (u'start', 1535583600000L), (u'synopsis', u'After a jealous Jade dumps Beck, she soon regrets it and recruits Tori to help get him back. Meanwhile, Trina puts on a one-woman show.'), (u'stills', [OrderedDict([(u'url', u'https://occ-0-461-1167.1.nflxso.net/art/c4190/c11e7315c16e47d55154ea117410bdf04e8c4190.jpg'), (u'h', 1080), (u'w', 1916)])]), (u'hiddenEpisodeNumbers', False), (u'runtime', 1418), (u'id', 70278610), (u'hd', True), (u'requiresPreReleasePin', False)]), 70172485)
10:40:22.736 T:14348   DEBUG: [Netflix] "Navigation::_get_timeline_markers" called
10:40:22.736 T:14348   DEBUG: [Netflix] "Navigation::_get_timeline_markers" returned: {'credit': {'start': 137, 'end': 195}, 'creditsOffset': 1407, 'watchedToEndOffset': 1336}
10:40:22.736 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: Platform information: ('Windows', 'Ash-HP-LAPTOP', '10', '10.0.17134', 'AMD64', 'Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')
10:40:22.736 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
10:40:22.736 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"id":1,"jsonrpc":"2.0","result":{"addon":{"addonid":"inputstream.adaptive","type":"kodi.inputstream"}}}
10:40:22.736 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive is installed.
10:40:22.736 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'properties': ['enabled'], 'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
10:40:22.737 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"id":1,"jsonrpc":"2.0","result":{"addon":{"addonid":"inputstream.adaptive","enabled":true,"type":"kodi.inputstream"}}}
10:40:22.737 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive 2.3.6 is enabled.
10:40:22.737 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive 2.3.6 is installed and enabled.
10:40:22.797 T:15572   DEBUG: ------ Window Init (DialogBusy.xml) ------
10:40:22.802 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
10:40:22.804 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
10:40:22.808 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
10:40:22.809 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
10:40:22.812 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
10:40:22.814 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
10:40:22.818 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
10:40:22.819 T:14348   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
10:40:22.820 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: Found Widevine binary at C:\Users\Ashley\AppData\Roaming\Kodi\cdm\widevinecdm.dll
10:40:22.869 T:14348   DEBUG: CAddonSettings[script.module.inputstreamhelper]: loading setting definitions
10:40:22.869 T:14348   DEBUG: CAddonSettings[script.module.inputstreamhelper]: trying to load setting definitions from old format...
10:40:22.870 T:14348   DEBUG: CAddonSettings[script.module.inputstreamhelper]: loading setting values
10:40:22.870 T:14348   DEBUG: [script.module.inputstreamhelper-0.3.3]: Widevine update check was made on 2018-11-04T10:37:52
10:40:23.521 T:14348   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'playcount'
                                            Traceback (most recent call last):
                                              File "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 253, in router
                                                infoLabels=params.get('infoLabels', {}))
                                              File "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 313, in play_video
                                                timeline_markers=self._get_timeline_markers(metadata))
                                              File "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\KodiHelper.py", line 985, in play_item
                                                'playcount': details[0]['playcount']}})
                                            KeyError: 'playcount'
                                            -->End of Python script error report<--
10:40:23.532 T:14348   DEBUG: CPythonInvoker::onExecutionDone(14, C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py)
10:40:23.536 T:15572   DEBUG: ------ Window Init (DialogNotification.xml) ------
10:40:23.595 T:14348 WARNING: CPythonInvoker(14, C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): the python script "C:\Users\Ashley\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
10:40:23.595 T:14348    INFO: Python interpreter stopped
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [*] Windows (x86/x64)
* [*] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Milhouse build 1103 (but also happens on older builds, also Windows 18.0-BETA4 Git:20181020-c83d227ac6 (20 Oct)

## Debug log
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2545730/kodi.log)

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
This will be fixed in 0.14.0. PR is #519.
