### ISSUE TITLE
Python Exception on launch

### ISSUE THREAD

**Issue by manayak** [asciidisco/plugin.video.netflix#545]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Netflix gives error after  Libreelec upgrade
### Prerequisites

* [ x] Are you running the latest version?

### Description

[Description of the bug or feature]
20:14:46.146 T:1938791072   ERROR: Control 550 in window 10025 has been asked to focus, but it can't
20:14:47.360 T:1498411888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 123, in router
                                                options = self.before_routing_action(params=params)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 867, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
20:14:47.605 T:1498411888 WARNING: CPythonInvoker(26, /storage/.kodi/addons/plugin.video.netflix/addon.py): the python script "/storage/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
20:14:47.616 T:1564185456   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
20:14:47.618 T:1938791072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by manayak** [comment]
Issue was Libreelec was auto Updated, so I reinstalled netflix addon and reboot . all worked.
This is due to updates.
Thank you
