### ISSUE TITLE
some movies are not replayed in kodi, while firefox plays them well

### ISSUE THREAD

**Issue by Mafeuser** [asciidisco/plugin.video.netflix#549]
*I'm submitting a ...*
  - [ *] bug report

## General information
some movies are played back in firefox browser, while not in kodi

### Prerequisites
Linux xubuntu 18.04, , kodi 18 (nightly) + netflix addon (0.13.19) through Netflix Repo, all installed today

### Description
When I run "The incredibles", the movie does not start and kodi.log is filled with the following

I tried to clean ESN (expert mode) and restart kodi, but didn't help. 

the log:

```
20:10:13.191 T:140388054795200  NOTICE: -----------------------------------------------------------------------
20:10:13.191 T:140388054795200  NOTICE: Starting Kodi (18.0-RC2 Git:20181123-8dfbf79). Platform: Linux x86 64-bit
20:10:13.191 T:140388054795200  NOTICE: Using Release Kodi x64 build
20:10:13.191 T:140388054795200  NOTICE: Kodi compiled Nov  4 2012 by GCC 7.3.0 for Linux x86 64-bit version 4.15.18 (266002)
20:10:13.191 T:140388054795200  NOTICE: Running on Ubuntu 18.04.1 LTS, kernel: Linux x86 64-bit version 4.15.0-39-generic
20:10:13.191 T:140388054795200  NOTICE: FFmpeg version/source: 4.0.3-Kodi
20:10:13.191 T:140388054795200  NOTICE: Host CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz, 4 cores available
20:10:13.191 T:140388054795200  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
20:10:13.191 T:140388054795200  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
20:10:13.191 T:140388054795200  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addons
20:10:13.191 T:140388054795200  NOTICE: special://masterprofile/ is mapped to: /home/user/.kodi/userdata
20:10:13.191 T:140388054795200  NOTICE: special://envhome/ is mapped to: /home/user
20:10:13.191 T:140388054795200  NOTICE: special://home/ is mapped to: /home/user/.kodi
20:10:13.191 T:140388054795200  NOTICE: special://temp/ is mapped to: /home/user/.kodi/temp
20:10:13.191 T:140388054795200  NOTICE: special://logpath/ is mapped to: /home/user/.kodi/temp
20:10:13.191 T:140388054795200  NOTICE: The executable running is: /usr/lib/x86_64-linux-gnu/kodi/kodi-x11
20:10:13.191 T:140388054795200  NOTICE: Local hostname: MyHost
20:10:13.191 T:140388054795200  NOTICE: Log File is located: /home/user/.kodi/temp/kodi.log
20:10:13.191 T:140388054795200  NOTICE: -----------------------------------------------------------------------
20:10:13.192 T:140388054795200    INFO: loading settings
20:10:13.192 T:140388054795200  NOTICE: special://profile/ is mapped to: special://masterprofile/
20:10:13.196 T:140388054795200   DEBUG: CSkinSettings: no <skinsettings> tag found
20:10:13.196 T:140388054795200  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
20:10:13.196 T:140388054795200  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
20:10:13.196 T:140388054795200  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
20:10:13.196 T:140388054795200  NOTICE: Default Video Player: VideoPlayer
20:10:13.196 T:140388054795200  NOTICE: Default Audio Player: paplayer
20:10:13.196 T:140388054795200  NOTICE: Disabled debug logging due to GUI setting. Level 0.
20:10:13.196 T:140388054795200  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
20:10:13.200 T:140388054795200  NOTICE: PulseAudio: Server found running - will try to use Pulse
20:10:13.202 T:140388054795200  NOTICE: Running database version Addons27
20:10:13.207 T:140388054795200  NOTICE: ADDON: audioencoder.kodi.builtin.aac v1.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: audioencoder.kodi.builtin.wma v1.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: game.controller.default v1.0.8 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: game.controller.snes v1.0.8 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: inputstream.adaptive v2.3.11 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: inputstream.rtmp v2.0.3 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.global.audioengine v1.0.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.global.filesystem v1.0.2 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.global.general v1.0.3 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.global.gui v5.12.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.global.main v1.0.13 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.global.network v1.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.audiodecoder v2.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.audioencoder v2.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.game v1.1.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.imagedecoder v2.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.peripheral v1.3.7 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.pvr v5.10.3 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.screensaver v2.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.vfs v2.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.videocodec v1.0.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.binary.instance.visualization v2.0.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: kodi.resource v1.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.album.universal v3.1.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.artists.universal v4.2.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.common.allmusic.com v3.2.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.common.fanart.tv v3.5.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.common.imdb.com v3.1.4 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.common.musicbrainz.org v2.2.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.common.theaudiodb.com v2.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.common.themoviedb.org v3.1.8 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.local v1.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.themoviedb.org v5.1.4 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: metadata.tvshows.themoviedb.org v3.0.6 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: peripheral.joystick v1.4.6 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: plugin.video.netflix v0.13.19 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: repository.netflix v1.0.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: repository.xbmc.org v3.1.4 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: resource.images.weathericons.default v1.1.8 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: resource.language.en_gb v2.0.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: resource.language.pl_pl v9.0.9 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: resource.uisounds.kodi v1.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: screensaver.xbmc.builtin.black v1.0.32 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: screensaver.xbmc.builtin.dim v1.0.47 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.addon.signals v0.0.3 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.certifi v2017.07.27.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.chardet v3.0.4 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.idna v2.6 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.inputstreamhelper v0.3.3 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.pil v1.1.7 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.pycryptodome v3.4.3 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.requests v2.19.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: script.module.urllib3 v1.22 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: service.xbmc.versioncheck v0.4.2 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: skin.estouchy v2.0.18 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: skin.estuary v2.0.15 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: visualization.spectrum v1.1.1 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: webinterface.default v18.x-2.4.6 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.addon v17.9.920 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.core v0.1.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.gui v5.14.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.json v10.0.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.python v2.26.0 installed
20:10:13.207 T:140388054795200  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
20:10:13.245 T:140388054795200   ERROR: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanSuspend'
20:10:13.245 T:140388054795200   ERROR: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanHibernate'
20:10:13.250 T:140387533494016 WARNING: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
20:10:13.250 T:140387533494016  NOTICE: Found 1 Lists of Devices
20:10:13.250 T:140387533494016  NOTICE: Enumerated PULSE devices:
20:10:13.250 T:140387533494016  NOTICE:     Device 1
20:10:13.251 T:140387533494016  NOTICE:         m_deviceName      : Default
20:10:13.251 T:140387533494016  NOTICE:         m_displayName     : Default
20:10:13.251 T:140387533494016  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
20:10:13.251 T:140387533494016  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
20:10:13.251 T:140387533494016  NOTICE:         m_channels        : FL, FR
20:10:13.251 T:140387533494016  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
20:10:13.251 T:140387533494016  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
20:10:13.251 T:140387533494016  NOTICE:         m_streamTypes     : No passthrough capabilities
20:10:13.251 T:140387533494016  NOTICE:     Device 2
20:10:13.251 T:140387533494016  NOTICE:         m_deviceName      : alsa_output.pci-0000_00_1b.0.analog-stereo
20:10:13.251 T:140387533494016  NOTICE:         m_displayName     : Built-in Audio Analog Stereo
20:10:13.251 T:140387533494016  NOTICE:         m_displayNameExtra: Speakers (PULSEAUDIO)
20:10:13.251 T:140387533494016  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
20:10:13.251 T:140387533494016  NOTICE:         m_channels        : FL, FR
20:10:13.251 T:140387533494016  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
20:10:13.251 T:140387533494016  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
20:10:13.251 T:140387533494016  NOTICE:         m_streamTypes     : No passthrough capabilities
20:10:13.253 T:140387525101312  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
20:10:13.735 T:140388054795200  NOTICE: Checking resolution 16
20:10:13.823 T:140388054795200  NOTICE: Using visual 0x21
20:10:13.832 T:140388054795200  NOTICE: VAAPI::Close - closing decoder context
20:10:13.840 T:140388054795200   ERROR: CYUVShaderGLSL::CYUVShaderGLSL - failed to open file gl_shader_frag_texture_lim.glsl
20:10:13.840 T:140388054795200  NOTICE: GL: No pixel shader, fixed pipeline in use
20:10:13.851 T:140388054795200  NOTICE: GL_VENDOR = Intel Open Source Technology Center
20:10:13.851 T:140388054795200  NOTICE: GL_RENDERER = Mesa DRI Intel(R) Sandybridge Mobile
20:10:13.851 T:140388054795200  NOTICE: GL_VERSION = 3.3 (Core Profile) Mesa 18.0.5
20:10:13.851 T:140388054795200  NOTICE: GL_SHADING_LANGUAGE_VERSION = 3.30
20:10:13.851 T:140388054795200  NOTICE: GL_EXTENSIONS = GL_3DFX_texture_compression_FXT1 GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_objects GL_ARB_shader_subroutine GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_sync GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_integer_mix GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_robustness GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NV_conditional_render GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_OES_EGL_image GL_S3_s3tc
20:10:13.983 T:140386825934592  NOTICE: Running database version Addons27
20:10:13.983 T:140386825934592  NOTICE: Running database version ViewModes6
20:10:13.983 T:140386825934592  NOTICE: Running database version Textures13
20:10:13.984 T:140386825934592  NOTICE: Running database version MyMusic72
20:10:13.986 T:140386825934592  NOTICE: Running database version MyVideos112
20:10:13.987 T:140386825934592  NOTICE: Running database version TV32
20:10:13.987 T:140386825934592  NOTICE: Running database version Epg12
20:10:13.988 T:140388054795200  NOTICE: start dvd mediatype detection
20:10:14.005 T:140388054795200  NOTICE:   load skin from: /usr/share/kodi/addons/skin.estuary (version: 2.0.15)
20:10:14.087 T:140388054795200 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
20:10:14.103 T:140388054795200  NOTICE: Register - new keyboard device registered on application->keyboard: Klawiatura (0000:0000)
20:10:14.103 T:140388054795200  NOTICE: Register - new mouse device registered on application->mouse: Mysz (0000:0000)
20:10:14.105 T:140388054795200  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
20:10:14.105 T:140388054795200  NOTICE: Loaded playercorefactory configuration
20:10:14.105 T:140388054795200  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
20:10:14.105 T:140388054795200  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
20:10:14.109 T:140388054795200  NOTICE: initialize done
20:10:14.109 T:140388054795200  NOTICE: Running the application...
20:10:14.111 T:140388054795200  NOTICE: starting zeroconf publishing
20:10:14.112 T:140386391529216  NOTICE: ES: Starting UDP Event server on port 9777
20:10:14.112 T:140386391529216  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
20:10:18.417 T:140386825934592   ERROR: GetDirectory - Error getting
20:10:36.495 T:140388054795200   ERROR: Previous line repeats 6 times.
20:10:36.495 T:140388054795200  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+%27%27%2C+%27plot%27%3A+u%27Czy+superbohaterowie+mog%5Cu0105+utrzyma%5Cu0107+swoj%5Cu0105+moc+w%5Cxa0tajemnicy%3F+Tej+niesamowitej+rodzinie+udaje+si%5Cu0119+to%5Cxa0a%5Cu017c+do...+chwili+pr%5Cxf3by.%27%2C+%27season%27%3A+None%2C+%27tvshowtitle%27%3A+%27%27%2C+%27title%27%3A+u%27Iniemamocni%27%2C+%27mediatype%27%3A+%27movie%27%2C+%27mpaa%27%3A+%27NFLX-7%2B%27%2C+%27cast%27%3A+%5Bu%27Sarah+Vowell%27%2C+u%27Teddy+Newton%27%2C+u%27Bud+Luckey%27%2C+u%27Elizabeth+Pe%5Cxf1a%27%2C+u%27Eli+Fucile%27%2C+u%27Maeve+Andrews%27%2C+u%27Lou+Romano%27%2C+u%27Samuel+L.+Jackson%27%2C+u%27Brad+Bird%27%2C+u%27John+Ratzenberger%27%2C+u%27Craig+T.+Nelson%27%2C+u%27Jason+Lee%27%2C+u%27Jean+Sincere%27%2C+u%27Wallace+Shawn%27%2C+u%27Spencer+Fox%27%2C+u%27Holly+Hunter%27%5D%2C+%27director%27%3A+u%27Brad+Bird%27%2C+%27genre%27%3A+u%27Filmy+uznane+przez+krytyk%5Cxf3w%27%2C+%27year%27%3A+2004%2C+%27duration%27%3A+6660%7D&video_id=70001989&pin=True
20:10:36.495 T:140386416707328  NOTICE: Creating InputStream
20:10:38.351 T:140385888093952   ERROR: Traceback (most recent call last):
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
20:10:38.351 T:140385888093952   ERROR:     self.process_request(request, client_address)
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
20:10:38.351 T:140385888093952   ERROR:     self.finish_request(request, client_address)
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
20:10:38.351 T:140385888093952   ERROR:     self.RequestHandlerClass(request, client_address, self)
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
20:10:38.351 T:140385888093952   ERROR:     self.handle()
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
20:10:38.351 T:140385888093952   ERROR:     self.handle_one_request()
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
20:10:38.351 T:140385888093952   ERROR:     method()
20:10:38.351 T:140385888093952   ERROR:   File "/home/user/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 38, in do_POST
20:10:38.351 T:140385888093952   ERROR:     self.wfile.write(base64.standard_b64decode(b64license))
20:10:38.351 T:140385888093952   ERROR:   File "/usr/lib/python2.7/base64.py", line 96, in standard_b64decode
20:10:38.352 T:140385888093952   ERROR:     return b64decode(s)
20:10:38.352 T:140385888093952   ERROR:   File "/usr/lib/python2.7/base64.py", line 75, in b64decode
20:10:38.352 T:140385888093952   ERROR:     return binascii.a2b_base64(s)
20:10:38.352 T:140385888093952   ERROR: TypeError: a2b_base64() argument 1 must be string or buffer, not bool
20:10:38.352 T:140386416707328   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
20:10:38.352 T:140386416707328   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
20:10:38.354 T:140386416707328   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+%27%27%2C+%27plot%27%3A+u%27Czy+superbohaterowie+mog%5Cu0105+utrzyma%5Cu0107+swoj%5Cu0105+moc+w%5Cxa0tajemnicy%3F+Tej+niesamowitej+rodzinie+udaje+si%5Cu0119+to%5Cxa0a%5Cu017c+do...+chwili+pr%5Cxf3by.%27%2C+%27season%27%3A+None%2C+%27tvshowtitle%27%3A+%27%27%2C+%27title%27%3A+u%27Iniemamocni%27%2C+%27mediatype%27%3A+%27movie%27%2C+%27mpaa%27%3A+%27NFLX-7%2B%27%2C+%27cast%27%3A+%5Bu%27Sarah+Vowell%27%2C+u%27Teddy+Newton%27%2C+u%27Bud+Luckey%27%2C+u%27Elizabeth+Pe%5Cxf1a%27%2C+u%27Eli+Fucile%27%2C+u%27Maeve+Andrews%27%2C+u%27Lou+Romano%27%2C+u%27Samuel+L.+Jackson%27%2C+u%27Brad+Bird%27%2C+u%27John+Ratzenberger%27%2C+u%27Craig+T.+Nelson%27%2C+u%27Jason+Lee%27%2C+u%27Jean+Sincere%27%2C+u%27Wallace+Shawn%27%2C+u%27Spencer+Fox%27%2C+u%27Holly+Hunter%27%5D%2C+%27director%27%3A+u%27Brad+Bird%27%2C+%27genre%27%3A+u%27Filmy+uznane+przez+krytyk%5Cxf3w%27%2C+%27year%27%3A+2004%2C+%27duration%27%3A+6660%7D&video_id=70001989&pin=True]
20:10:38.354 T:140386416707328  NOTICE: CVideoPlayer::OnExit()
20:10:38.371 T:140388054795200  NOTICE: CVideoPlayer::CloseFile()
20:10:38.371 T:140388054795200  NOTICE: VideoPlayer: waiting for threads to exit
20:10:38.371 T:140388054795200  NOTICE: VideoPlayer: finished waiting
```

**Comment by caphm** [comment]
It's probably due to the recent changes by Netflix. Try the beta from #519

**Comment by Mafeuser** [comment]
sure.
Can I do it in easy way, for example how can I download plugin.video.netflix.zip that contains Your pull request, but when Your PR will be merged newer version will be taken from repository.netflix- repo.
