### ISSUE TITLE
[Kodi] SSL error with HTTPS requests <class 'requests.exceptions.SSLError'> (Debian, X64_86)

### ISSUE THREAD

**Issue by wb9688** [asciidisco/plugin.video.netflix#58]
When I start Kodi, I get the error "Netflix error - Check the log for more information". I also can't open the Netflix addon.

Kodi: 2f67109f60
inputstream.adaptive: a7e84de
Debian: Unstable
Widevine: 1.4.8.962
```
﻿17:24:09.098 T:140696603409280  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:24:09.098 T:140696603409280  NOTICE: -----------------------------------------------------------------------
17:24:09.098 T:140696603409280  NOTICE: Starting Kodi (18.0-ALPHA1 Git:20170415-2f67109). Platform: Linux x86 64-bit
17:24:09.098 T:140696603409280  NOTICE: Using Release Kodi x64 build
17:24:09.098 T:140696603409280  NOTICE: Kodi compiled Apr 17 2017 by GCC 6.3.0 for Linux x86 64-bit version 4.9.18 (264466)
17:24:09.098 T:140696603409280  NOTICE: Running on Debian GNU/Linux 9 (stretch), kernel: Linux x86 64-bit version 4.9.0-2-amd64
17:24:09.098 T:140696603409280  NOTICE: FFmpeg version/source: 3.2.4-1
17:24:09.098 T:140696603409280  NOTICE: Host CPU: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz, 4 cores available
17:24:09.098 T:140696603409280  NOTICE: special://xbmc/ is mapped to: /usr/local/share/kodi
17:24:09.098 T:140696603409280  NOTICE: special://xbmcbin/ is mapped to: /usr/local/lib/kodi
17:24:09.098 T:140696603409280  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/local/lib/kodi/addons
17:24:09.098 T:140696603409280  NOTICE: special://masterprofile/ is mapped to: /home/wb9688/.kodi/userdata
17:24:09.098 T:140696603409280  NOTICE: special://envhome/ is mapped to: /home/wb9688
17:24:09.098 T:140696603409280  NOTICE: special://home/ is mapped to: /home/wb9688/.kodi
17:24:09.098 T:140696603409280  NOTICE: special://temp/ is mapped to: /home/wb9688/.kodi/temp
17:24:09.098 T:140696603409280  NOTICE: special://logpath/ is mapped to: /home/wb9688/.kodi/temp
17:24:09.098 T:140696603409280  NOTICE: The executable running is: /usr/local/lib/kodi/kodi.bin
17:24:09.098 T:140696603409280  NOTICE: Local hostname: wb9688-nuc6i3syh
17:24:09.098 T:140696603409280  NOTICE: Log File is located: /home/wb9688/.kodi/temp//kodi.log
17:24:09.098 T:140696603409280  NOTICE: -----------------------------------------------------------------------
17:24:09.111 T:140696603409280  NOTICE: load settings...
17:24:09.121 T:140696603409280   ERROR: PulseAudio: Failed to connect context
17:24:09.121 T:140696603409280  NOTICE: PulseAudio might not be running. Context was not created.
17:24:09.144 T:140696603409280  NOTICE: Found 1 Lists of Devices
17:24:09.144 T:140696603409280  NOTICE: Enumerated ALSA devices:
17:24:09.144 T:140696603409280  NOTICE:     Device 1
17:24:09.144 T:140696603409280  NOTICE:         m_deviceName      : @
17:24:09.144 T:140696603409280  NOTICE:         m_displayName     : Default (HDA Intel PCH ALC283 Analog)
17:24:09.144 T:140696603409280  NOTICE:         m_displayNameExtra:
17:24:09.144 T:140696603409280  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
17:24:09.144 T:140696603409280  NOTICE:         m_channels        : FL, FR
17:24:09.144 T:140696603409280  NOTICE:         m_sampleRates     : 48000
17:24:09.144 T:140696603409280  NOTICE:         m_dataFormats     : AE_FMT_S32NE
17:24:09.144 T:140696603409280  NOTICE:         m_streamTypes     : No passthrough capabilities
17:24:09.144 T:140696603409280  NOTICE:     Device 2
17:24:09.145 T:140696603409280  NOTICE:         m_deviceName      : @:CARD=PCH,DEV=0
17:24:09.145 T:140696603409280  NOTICE:         m_displayName     : HDA Intel PCH
17:24:09.145 T:140696603409280  NOTICE:         m_displayNameExtra: ALC283 Analog
17:24:09.145 T:140696603409280  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
17:24:09.145 T:140696603409280  NOTICE:         m_channels        : FL, FR
17:24:09.145 T:140696603409280  NOTICE:         m_sampleRates     : 48000
17:24:09.145 T:140696603409280  NOTICE:         m_dataFormats     : AE_FMT_S32NE
17:24:09.145 T:140696603409280  NOTICE:         m_streamTypes     : No passthrough capabilities
17:24:09.145 T:140696603409280  NOTICE:     Device 3
17:24:09.145 T:140696603409280  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=0
17:24:09.145 T:140696603409280  NOTICE:         m_displayName     : HDA Intel PCH
17:24:09.145 T:140696603409280  NOTICE:         m_displayNameExtra: SAM T22D390 on HDMI #0
17:24:09.145 T:140696603409280  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:24:09.145 T:140696603409280  NOTICE:         m_channels        : FL, FR
17:24:09.145 T:140696603409280  NOTICE:         m_sampleRates     : 32000,44100,48000
17:24:09.145 T:140696603409280  NOTICE:         m_dataFormats     : AE_FMT_RAW,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
17:24:09.145 T:140696603409280  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
17:24:09.145 T:140696603409280  NOTICE:     Device 4
17:24:09.145 T:140696603409280  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=1
17:24:09.145 T:140696603409280  NOTICE:         m_displayName     : HDA Intel PCH
17:24:09.145 T:140696603409280  NOTICE:         m_displayNameExtra: HDMI #1
17:24:09.145 T:140696603409280  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:24:09.145 T:140696603409280  NOTICE:         m_channels        : FL, FR
17:24:09.145 T:140696603409280  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
17:24:09.145 T:140696603409280  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
17:24:09.145 T:140696603409280  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
17:24:09.145 T:140696603409280  NOTICE:     Device 5
17:24:09.145 T:140696603409280  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=2
17:24:09.145 T:140696603409280  NOTICE:         m_displayName     : HDA Intel PCH
17:24:09.145 T:140696603409280  NOTICE:         m_displayNameExtra: HDMI #2
17:24:09.145 T:140696603409280  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
17:24:09.145 T:140696603409280  NOTICE:         m_channels        : FL, FR
17:24:09.145 T:140696603409280  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
17:24:09.145 T:140696603409280  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
17:24:09.145 T:140696603409280  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
17:24:09.146 T:140696603409280  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
17:24:09.147 T:140696603409280  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
17:24:09.147 T:140696603409280  NOTICE: Default Video Player: VideoPlayer
17:24:09.147 T:140696603409280  NOTICE: Default Audio Player: paplayer
17:24:09.147 T:140696603409280  NOTICE: Disabled debug logging due to GUI setting. Level 0.
17:24:09.147 T:140696603409280  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
17:24:09.147 T:140696603409280  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
17:24:09.147 T:140696603409280  NOTICE: Loaded playercorefactory configuration
17:24:09.147 T:140696603409280  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
17:24:09.147 T:140696603409280  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
17:24:09.149 T:140696603409280  NOTICE: Running database version Addons27
17:24:09.183 T:140696603409280  NOTICE: Checking resolution 16
17:24:09.234 T:140696603409280  NOTICE: Using visual 0x20
17:24:09.300 T:140696603409280  NOTICE: VAAPI::Close - closing decoder context
17:24:09.309 T:140696603409280  NOTICE: GL_VENDOR = Intel Open Source Technology Center
17:24:09.309 T:140696603409280  NOTICE: GL_RENDERER = Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
17:24:09.309 T:140696603409280  NOTICE: GL_VERSION = 3.0 Mesa 13.0.6
17:24:09.309 T:140696603409280  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.30
17:24:09.310 T:140696603409280  NOTICE: GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_shader_atomic_counter_ops GL_ARB_shader_clock GL_EXT_shader_samples_identical GL_KHR_texture_compression_astc_sliced_3d GL_MESA_shader_integer_functions
17:24:09.479 T:140695746639616  NOTICE: Running database version Addons27
17:24:09.479 T:140695746639616  NOTICE: Running database version ViewModes6
17:24:09.480 T:140695746639616  NOTICE: Running database version Textures13
17:24:09.481 T:140695746639616  NOTICE: Running database version MyMusic62
17:24:09.482 T:140695746639616  NOTICE: Running database version MyVideos108
17:24:09.483 T:140695746639616  NOTICE: Running database version TV30
17:24:09.483 T:140695746639616  NOTICE: Running database version Epg11
17:24:09.486 T:140696603409280  NOTICE: start dvd mediatype detection
17:24:09.555 T:140696603409280 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
17:24:09.611 T:140696603409280  NOTICE: Register - new joystickemulation device registered on application->1: Keyboard player (0000:0000)
17:24:09.613 T:140696603409280  NOTICE: initialize done
17:24:09.613 T:140696603409280  NOTICE: Running the application...
17:24:09.615 T:140696603409280  NOTICE: starting zeroconf publishing
17:24:09.615 T:140696603409280  NOTICE: starting upnp client
17:24:09.631 T:140694429607680  NOTICE: ES: Starting UDP Event server on port 9777
17:24:09.631 T:140694429607680  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
17:24:13.466 T:140695360935680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
                                            Traceback (most recent call last):
                                              File "/home/wb9688/.kodi/addons/plugin.video.netflix/service.py", line 12, in <module>
                                                from resources.lib.NetflixHttpRequestHandler import NetflixHttpRequestHandler
                                              File "/home/wb9688/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 25, in <module>
                                                sub_res_handler = NetflixHttpSubRessourceHandler(kodi_helper=kodi_helper, netflix_session=netflix_session)
                                              File "/home/wb9688/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 27, in __init__
                                                self.prefetch_login()
                                              File "/home/wb9688/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 36, in prefetch_login
                                                self.netflix_session.refresh_session_data(account=self.credentials)
                                              File "/home/wb9688/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 1565, in refresh_session_data
                                                response = self._session_get(component='profiles')
                                              File "/home/wb9688/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 1949, in _session_get
                                                response = self.session.get(url=url, verify=self.verify_ssl, params=params)
                                              File "/home/wb9688/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 501, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/home/wb9688/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/wb9688/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/wb9688/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 497, in send
                                                raise SSLError(e, request=request)
                                            SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
                                            -->End of Python script error report<--
17:24:19.193 T:140696603409280  NOTICE: Storing total System Uptime
17:24:19.193 T:140696603409280  NOTICE: Saving settings
17:24:19.199 T:140696603409280  NOTICE: Saving skin settings
17:24:19.200 T:140696603409280  NOTICE: stop all
17:24:19.201 T:140696603409280  NOTICE: stop player
17:24:19.201 T:140696603409280  NOTICE: ES: Stopping event server
17:24:19.201 T:140696603409280  NOTICE: stopping upnp
17:24:19.352 T:140696603409280  NOTICE: stopping zeroconf publishing
17:24:19.641 T:140694429607680  NOTICE: ES: UDP Event server stopped
17:24:19.641 T:140696603409280  NOTICE: stop dvd detect media
17:24:19.817 T:140696603409280  NOTICE: closing down remote control service
17:24:19.817 T:140696603409280  NOTICE: stopped
17:24:20.018 T:140696603409280  NOTICE: destroy
17:24:20.018 T:140696603409280  NOTICE: unload skin
17:24:20.062 T:140696603409280  NOTICE: unload sections
17:24:20.063 T:140696603409280  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:24:20.112 T:140696603409280  NOTICE: application stopped...
```

**Comment by asciidisco** [comment]
Looks like a Problem in the SSL stack (at a first glance).
Could you do me a favour & disable the SSL verification option in the plugin settings & then restart Kodi?

**Comment by wb9688** [comment]
That gives the same error…

**Comment by asciidisco** [comment]
Does 
```
curl -L 'https://www.netflix.com/Login' -H 'Pragma: no-cache' -H 'Origin: https://www.netflix.com' -H 'Accept-Language: en' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36' -H 'Cache-Control: no-cache' -vv
```
give you back proper HTML?

Do other plugins work that use https connections?
Does your box boot in to Kodi right away? (I´ve seen problems if the network/internet connection isn't available at Kodi startup) If so, delaying Kodi start until the network is available should help (at least until we fixed https://github.com/asciidisco/plugin.video.netflix/issues/23)

If the first two answers would be `yes` & the last would be `no` then I´m out of ideas. I don't have a 64bit Debian box here to test myself.

**Comment by asciidisco** [comment]
Maybe also related to this?
http://forum.kodi.tv/showthread.php?tid=304600

**Comment by wb9688** [comment]
That `curl` command gives me proper HTML. I just tested the YouTube add-on, but it gives me another bunch of SSL errors, but then that there's some `TypeError` in the `cffi` bindings for `openssl` in the `cryptography` package. My box doesn't boot into Kodi right away. Btw I forgot to mention that Kodi outputs a lot of `extern "Python": function Cryptography_locking_cb() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.`. And when I make a HTTPS request with `requests` in Python 2 and 3, I don't get any error.

**Comment by asciidisco** [comment]
Hmm, I must admit, this is beyond my knowledge, but I can tell you, you´re not the only one experiencing this issue (with Kodi). There´s a thread [here](https://github.com/pyca/cryptography/issues/3282) where people discussed the origin of the issue & a possible fix for Ubuntu (might apply to Debian as well)

**Comment by wb9688** [comment]
I already have version `1.7.1` of the `cryptography` package.

**Comment by asciidisco** [comment]
Out of ideas. Also it seems a bit beyond the scope of the plugin.
I´ll leave the issue open & adapt the headline, maybe someone else will come across & has some ideas about this.

**Comment by wb9688** [comment]
It started working after I removed the old `cryptography` package that
`pip` installed once. Thanks!

**Comment by asciidisco** [comment]
Great \o/
Guess we could file this under "the joy of Linux" then :D

**Comment by wb9688** [comment]
Yeah, but `pip` shouldn't have installed it in the first place, because it
was already installed through `apt`.

**Comment by ThorstenHackbarth** [comment]
$ sudo pip uninstall cryptography
fixed it. Thanks a lot!
