### ISSUE TITLE
Search doesn't work on 0.13.21

### ISSUE THREAD

**Issue by ido-ran** [asciidisco/plugin.video.netflix#581]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

When I try to search it show error. I've copied the error reported in the log bellow.
I tried to search in two people we have under my account.

### Prerequisites

* [x] Are you running the latest version?

### Description

```
20:33:28.811 T:1620546416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 265, in router
                                                return self.show_search_results(params.get('term'))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 362, in show_search_results
                                                'cache': True}))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                              File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
                                              File "/usr/lib/python2.7/httplib.py", line 438, in begin
                                              File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
                                              File "/usr/lib/python2.7/socket.py", line 480, in readline
                                            timeout: timed out
                                            -->End of Python script error report<--
20:33:29.095 T:1620546416 WARNING: CPythonInvoker(30, /storage/.kodi/addons/plugin.video.netflix/addon.py): the python script "/storage/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
20:33:29.097 T:1570190192   ERROR: Traceback (most recent call last):
20:33:29.098 T:1570190192   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
20:33:29.098 T:1940496976   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?action=search_result&term=good+place
20:33:29.098 T:1570190192   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
20:33:29.098 T:1570190192   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
20:33:29.098 T:1570190192   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
20:33:29.098 T:1570190192   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
20:33:29.098 T:1570190192   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
20:33:29.099 T:1570190192   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
20:33:29.099 T:1570190192   ERROR: error: [Errno 32] Broken pipe
20:33:29.099 T:1940496976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=search_result&term=good+place) failed

```
### Steps to Reproduce

1. Login
2. Select a person
3. Search

**Expected behavior:** [What you expected to happen]

The search result should show up

**Actual behavior:** [What actually happened]

An error show up

## Context (Environment)

Rpi 3
LibreElec

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

**Comment by ido-ran** [comment]
Might be duplicate of #573
