### ISSUE TITLE
0.13.21/head + Kodi 18rc4/head; unable to edit credentials: "Error Contents: cannot import name HTTPSHandler"

### ISSUE THREAD

**Issue by jole7** [asciidisco/plugin.video.netflix#590]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [X] support request

I've got Kodi
```
	18.0-RC4 Git:20181218-2441415bb0 Media Center Kodi
```

installed.

Netflix plugin's installed
```
	cd /home/jole/.kodi/addons/plugin.video.netflix
	git log | head
		commit 277499edb62447bc9ed4319d8478556937ecea40
		Author: libdev <liberty.developer@xmail.net>
		Date:   Mon Dec 3 01:27:30 2018 +0100

		    Version bump 0.13.21

		commit c2d113597bfee4ca1a4c4e4ec4cfca3ed158ad5d
		Author: libdev <liberty.developer@xmail.net>
		Date:   Sun Dec 2 20:36:15 2018 +0100
```

python setup includes,
```
	pip2 show pycryptodomex
		Name: pycryptodomex
		Version: 3.4.6
		Summary: Cryptographic library for Python
		Home-page: http://www.pycryptodome.org
		Author: Helder Eijs
		Author-email: helderijs@gmail.com
		License: UNKNOWN
		Location: /usr/lib64/python3.6/site-packages
		Requires:
		Required-by:

	python2
		Python 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC] on linux2
		Type "help", "copyright", "credits" or "license" for more information.
		>>> from urllib2 import HTTPSHandler
```

In Kodi, @ just-installed Netflix settings
```
	https://i.imgur.com/OCRn9z8.png
```

there's an account pre-populated,
```
	30059c
```

I've no idea where that's from.  I need to enter *my* credentials.

When I click on it to edit, I just get a dialog
```
	Netflix Error
	Check the log for more information
```

and in log
```
	cat kodi.log
		19:44:27.639 T:139930857641728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
			 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
			Error Type: <type 'exceptions.ImportError'>
			Error Contents: cannot import name HTTPSHandler
			Traceback (most recent call last):
			  File "/home/jole/.kodi/addons/plugin.video.netflix/addon.py", line 12, in <module>
			    from resources.lib.Navigation import Navigation
			  File "/home/jole/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 28, in <module>
			    from resources.lib.KodiHelper import KodiHelper
			  File "/home/jole/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 21, in <module>
			    from UniversalAnalytics import Tracker
			  File "/home/jole/.kodi/addons/plugin.video.netflix/resources/lib/UniversalAnalytics/__init__.py", line 1, in <module>
			    import Tracker
			  File "/home/jole/.kodi/addons/plugin.video.netflix/resources/lib/UniversalAnalytics/Tracker.py", line 11, in <module>
			    from urllib2 import Request, HTTPSHandler
			ImportError: cannot import name HTTPSHandler
			-->End of Python script error report<--
```

**Comment by mutluerol** [comment]
18:43:11.526 T:140004828935936   ERROR: Traceback (most recent call last):
18:43:11.526 T:140004828935936   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 290, in _handle_request_noblock
18:43:11.527 T:140004828935936   ERROR:     self.process_request(request, client_address)
18:43:11.527 T:140004828935936   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 318, in process_request
18:43:11.527 T:140004828935936   ERROR:     self.finish_request(request, client_address)
18:43:11.527 T:140004828935936   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
18:43:11.527 T:140004828935936   ERROR:     self.RequestHandlerClass(request, client_address, self)
18:43:11.527 T:140004828935936   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
18:43:11.527 T:140004828935936   ERROR:     self.handle()
18:43:11.527 T:140004828935936   ERROR:   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
18:43:11.527 T:140004828935936   ERROR:     self.handle_one_request()
18:43:11.527 T:140004828935936   ERROR:   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
18:43:11.527 T:140004828935936   ERROR:     method()
18:43:11.527 T:140004828935936   ERROR:   File "/home/erol/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 69, in do_GET
18:43:11.527 T:140004828935936   ERROR:     dolby, hevc, hdr, dolbyvision, vp9)
18:43:11.527 T:140004828935936   ERROR:   File "/home/erol/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 244, in load_manifest
18:43:11.527 T:140004828935936   ERROR:     data = self.__decrypt_payload_chunks(resp['payloads'])
18:43:11.527 T:140004828935936   ERROR:   File "/home/erol/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 332, in __decrypt_payload_chunks
18:43:11.527 T:140004828935936   ERROR:     decrypted_payload = decrypted_payload[1]['payload']
18:43:11.527 T:140004828935936   ERROR: KeyError: 1

**Comment by Jalle19** [comment]
Same issue here

**Comment by ShadowBr0ther** [comment]
Follow this guide:

https://www.pcwelt.de/a/einbau-von-netflix-und-amazon-prime-in-kodi-mit-plug-ins,3451924

Install Widevine solved the issue.

**Comment by jole7** [comment]
In current Kodi 18, Widevine install is not separately required, It's installed/updated by script.module.inpustreamhelper:

./addons/script.module.inputstreamhelper/README.md (md)                                                                                        
	...
	* Automatically installs Widevine CDM on supported platforms (optional)
	  * Keeps Widevine CDM up-to-date with the latest version available (Kodi 18 and higher)
	  * Checks for missing depending libraries by parsing the output from  `ldd` (Linux)


With this Kodi18 instance, InputStreamHelper 2018.02.21 v0.3.3 is installed.

**Comment by barrerajl** [comment]
Similar issue here: But the log says:

```
MCAddon9xbmcaddon5AddonE
23:45:19.267 T:1774134000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/xbian/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/xbian/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 119, in router
                                                return self.switch_account()
                                              File "/home/xbian/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 814, in switch_account
                                                self._check_response(self.call_netflix_service({'method': 'logout'}))
                                              File "/home/xbian/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
```
