### ISSUE TITLE
Failing to load profile - KeyError: 'user'

### ISSUE THREAD

**Issue by nickston3** [asciidisco/plugin.video.netflix#598]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [ # ] support request

### Prerequisites

* [ # ] Are you running the latest version?
Yes - 0.13.21

### Description

Slowly working my way through troubleshooting a new install. After disabling certificate verfication I can log in and see the list of my profiles, however trying to select a profiles takes a long time to load and fails with a generic ""

Looking at the logs I can see the below Stack Trace:

> 22:13:17.429 T:2478832448   ERROR: /home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
22:15:19.191 T:2891553600   ERROR: Previous line repeats 1 times.
22:15:19.191 T:2891553600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'user'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 158, in router
                                                return self.show_video_lists(widget_display=widget_display)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 565, in show_video_lists
                                                widget_display=widget_display)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 294, in build_main_menu_listing
                                                for video_list_id in video_list_ids['user']:
                                            KeyError: 'user'
                                            -->End of Python script error report<--
22:15:19.198 T:2969561920  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
22:15:19.298 T:2891553600 WARNING: CPythonInvoker(7, /home/kodi/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
22:15:19.311 T:2743761728   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?action=video_lists&profile_id=7XTYYBHDJBGWHO6MDSOENX3O2A
22:15:19.324 T:2987812928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=video_lists&profile_id=7XTYYBHDJBGWHO6MDSOENX3O2A) failed

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Shows are listed per profile

**Actual behavior:** [What actually happened]
Spinning loading wheel and failure to load

## Context (Environment)
Linux Mint 17 i386, Kodi 18

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ # ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ # ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jakermx** [comment]
Try to change your email, it could contain non utf-8 chars.

Where are you located?
What device are u using?
What bw do you have ?
What is the response time while pinging netflix.com?
