### ISSUE TITLE
Video not playing (again) kodi 18 rc1

### ISSUE THREAD

**Issue by vozer** [asciidisco/plugin.video.netflix#608]
*I'm submitting a ...*
  - [x bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ x] Are you running the latest version?

### Description

Again i can't play any videos. When i want to start the video it loads 2 times (circle) and 
Stays in the menu. 
I know there are other issues about it but they are closed and solved with Version . 21

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)
.
### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
.
Libreelec with kodi 18 rc  8.95.3 Beta

## Other information

I Uninstalled and reinstalled, tried different versions, reboot, logged in with different accounts. It started working around new year and now again not. 

Changing esn i don't know how to do that or if it's aplicable to me.

**Comment by rmeshksar** [comment]
I have exact same problem with Kodi 18.0 RC5.

**Comment by cvanaken** [comment]
Me too in LibreELEC release: WeTek_Hub.arm-8.95.003 

NOTICE: Creating InputStream
20:28:44.021 T:3471881072   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
20:28:45.160 T:3393184624   ERROR: Traceback (most recent call last):
20:28:45.420 T:3393184624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
20:28:45.420 T:3393184624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
20:28:45.420 T:3393184624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
20:28:45.420 T:3393184624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
20:28:45.420 T:3393184624   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
20:28:45.420 T:3393184624   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
20:28:45.420 T:3393184624   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 69, in do_GET
20:28:45.421 T:3393184624   ERROR:     dolby, hevc, hdr, dolbyvision, vp9)
20:28:45.421 T:3393184624   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 219, in load_manifest
20:28:45.422 T:3393184624   ERROR:     request_data = self.__generate_msl_request_data(manifest_request_data)
20:28:45.424 T:3393184624   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 547, in __generate_msl_request_data
20:28:45.424 T:3393184624   ERROR:     plaintext=self.__generate_msl_header())
20:28:45.424 T:3393184624   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 622, in __encrypt
20:28:45.424 T:3393184624   ERROR:     return json.dumps(self.crypto.encrypt(plaintext, self.nx_common.get_esn(), self.sequence_number))
20:28:45.424 T:3393184624   ERROR: AttributeError: 'MSL' object has no attribute 'sequence_number'
20:28:45.424 T:3471881072   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)

**Comment by hobodrifterdavid** [comment]
Heads up, Netflix have changed their API a little a couple of days ago. The manifest now has a slightly different format. Nothing too major. I guess that's the source of the issues.

**Comment by peno64** [comment]
I have no problems with netflix on Kodi 18.0 RC5 on Raspberry Pi.
