### ISSUE TITLE
Kodi 18 RC5.2 Android Netflix plugin gives a python error

### ISSUE THREAD

**Issue by Vitocorl** [asciidisco/plugin.video.netflix#614]
*I'm submitting a ...*
  - [ ] support request

* [ ] Are you running the latest version?
Yes
### Installation
* [ ] I´m using the Netflix Repo

### Operating System
* [ ] Android

#### Additional informatin on the environment
Xiaomi MiBox S

## Debug log
https://paste.kodi.tv/rigekodimu.kodi

**Comment by ImNtReal** [comment]
I think I'm running into the same issue on Kodi 18 final.

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/home/imntreal/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/imntreal/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/imntreal/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 119, in router
                                                return self.switch_account()
                                              File "/home/imntreal/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 814, in switch_account
                                                self._check_response(self.call_netflix_service({'method': 'logout'}))
                                              File "/home/imntreal/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
```

**Comment by rkkoszewski** [comment]
Same issue here, also on a Mi Box S, with both "Connection refused" errors and "TypeError: b2a_base64() argument 1 must be string or buffer, not None" error. Seems like there are several related issues around here, probably something has changed in Netflix and needs to be addressed in order for this plugin to work. Is the plugin working currently for anybody?

**Comment by Vitocorl** [comment]
The plugin is working for me, on Zidoo H6 Pro, which is Android 7.1. It does not work on Xiaomi MiBox S and Mecool KM9, which are Android TV 8.1, giving the same widevine errors, so i guess it has something to do with the android version 8.1 or Android TV....

**Comment by joaosagrath** [comment]
In Xiaomi Mi Box 4K it's the same.
