### ISSUE TITLE
Netlfix plugin does not work. I get an error from the Netflix addon telling me to check the log.

### ISSUE THREAD

**Issue by deutne** [asciidisco/plugin.video.netflix#617]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X ] support request

## General information
I am getting an error on the Netflix plugin. I am hoping someone can look at my kodi log file. I tried to follow the directions posted on github with the plugin.

### Prerequisites

* [x ] Are you running the latest version?

### Steps to Reproduce

When I start up Kodi, I get an error from the Netflix plugin. It just says that I should check the log. When I try to start the plugin, the same thing happens.

**Expected behavior:** I was hoping to get Netflix to actually work. I have a paid account with them.

**Actual behavior:** The netflix plugin does not work.

### Installation

* [x ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM)
* [ ] Android

#### Additional information on the environment
Rapsberry Pi 3B+, Raspbian stretch, Kodi 18

## Debug log
http://sprunge.us/rVPP97

## Other information
I would provide you with more info, but I am not sure how to check the versions of everything.

**Comment by lutel** [comment]
Same here, with log:

`2:55:04.700 T:140427689412352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 123, in router
                                                options = self.before_routing_action(params=params)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 867, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1054, in call_netflix_service
                                                parsed_json = json.loads(data, object_pairs_hook=OrderedDict)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--`

**Comment by lutel** [comment]
Same here:

> 2:55:04.700 T:140427689412352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 123, in router
                                                options = self.before_routing_action(params=params)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 867, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1054, in call_netflix_service
                                                parsed_json = json.loads(data, object_pairs_hook=OrderedDict)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

**Comment by strackx** [comment]
I got the same problem. Following these instructions:
[https://laclaro.wordpress.com/2017/10/14/rpi-streaming-station-with-amazon-instant-video-and-netflix/](url)
I managed to resolve it. :)

**Comment by snock** [comment]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

### Prerequisites

* [X] Are you running the latest version? Yes

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Context (Environment)

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

raspberry 3b+ and Rasparch 
Linux archpi 4.14.97-1-ARCH #1 SMP Tue Feb 5 20:10:34 UTC 2019 armv7l GNU/Linux


## Debug log
https://pastebin.com/g8ChN9tE

**Comment by skylarmt** [comment]
> I got the same problem. Following these instructions:
> [https://laclaro.wordpress.com/2017/10/14/rpi-streaming-station-with-amazon-instant-video-and-netflix/](url)
> I managed to resolve it. :)

That page is not only close to two years old, it's a 404 error.

**Comment by mivalsten** [comment]
@snock 
`ImportError: No module named Cryptodome.Random`

You lack dependencies, issue following commands in your shell to install cryptodome module for python2.7:
`python2.7 -m pip install pycryptodome pycryptodomex`

**Comment by sorin-pop** [comment]
Apparently having the same issue, just out of the blue, without changing anything. Yesterday the addon was working fine, today, when choosing an account within my family gives "Netflix error check log for more information"
