### ISSUE TITLE
Netlix error, check log for details

### ISSUE THREAD

**Issue by JeroenTuinstra** [asciidisco/plugin.video.netflix#628]
*I'm submitting a ...*
  - [*] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [*] Are you running the latest version?

### Description

It seems that somehow the addon cannot login to netflix when Kodi starts. Not untill the actual addon has run once do the features of teh Aura skin appear. 

### Steps to Reproduce

1. Install everything as should be. 
2. restart kodi
3. error message appears
4. widgets that use netflix information disappear
5. start netflix addon, exit out of addon
6. widgets appear

**Expected behavior:** What I expected is that when Kodi starts the addon would be able to login into the account and show the requested information in the widget. 

**Actual behavior:** It doesn't seem to login to the netflix account, selecting the proper profile (there are 5) and starting the widgets properly.

## Context (Environment)
Windows 10 - Kodi 18 - Netflix 0.13.21
Proper netflix account. 

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [*] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [* ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://www.dropbox.com/s/sj1x79f3vih4f0w/kodi.log?dl=0

![error-netflix](https://user-images.githubusercontent.com/47460053/52500091-67c15100-2bdd-11e9-9567-89705f9d84cb.jpg)
![loginhappens](https://user-images.githubusercontent.com/47460053/52500144-90494b00-2bdd-11e9-8239-2098af678b9e.jpg)
![netflixworks](https://user-images.githubusercontent.com/47460053/52500149-950dff00-2bdd-11e9-9bbe-e72cef3899dc.jpg)
![how it should work](https://user-images.githubusercontent.com/47460053/52500222-c2f34380-2bdd-11e9-8126-0aee9dfd1902.jpg)

**Comment by Choukajohn** [comment]
Hi,
Same issue here except I am on Linux (x86/x64).

**Comment by diogogmt** [comment]
Same problem here;

```
00:17:01.033 T:140311080710144   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
00:17:01.326 T:140310922385152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 111] Connection refused>
                                            Traceback (most recent call last):
                                              File "/home/diogo/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/diogo/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/diogo/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 123, in router
                                                options = self.before_routing_action(params=params)
                                              File "/home/diogo/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/diogo/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 867, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/home/diogo/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 111] Connection refused>
                                            -->End of Python script error report<--
00:17:01.348 T:140310922385152 WARNING: CPythonInvoker(4, /home/diogo/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/diogo/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
00:17:01.368 T:140310930777856   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
00:17:01.378 T:140311080710144   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
```

**Comment by Antidote00** [comment]
Same error here, using freshly installed Kodi 18 on Raspberry PI 3. 
Log: https://pastebin.com/nTY7Yyx2

Thanks for any tips and help :)

**Comment by kkr0kk** [comment]
I confirm this BUG on a fresh install RPI3 kodi 18.0-1

**Comment by tenbergen** [comment]
Ditto, same as @kkr0kk. Fresh install of Kodi 18 on Raspian, RPi 3b+. Latest apt-get and dist-update.

**Comment by jcreixell** [comment]
Same here

**Comment by lynix** [comment]
Had this before on Rpi3 B+ with Arch Linux ARM and kodi-rbp3-18.0-1. Works fine since updating to 18.1-1 :)

**Comment by Choukajohn** [comment]
Same here, works fine since 18.1 update on Linux (x86/x64).

**Comment by JeroenTuinstra** [comment]
Upgraded to 18.1 on windows 10. Same problem still. Netflix app still on 0.13.21. Netflix addon respository still not showing any updates to netflix. Problem remains.

**Comment by tmsbrdrs** [comment]
Same problem here on fire stick v2 with Kodi 18.1, add-on version 0.13.21. 
In my case, I originally could run everything on Kodi version 18 but had to reset. Once I reinstalled Kodi, one of the first add-ons I installed is Netflix via the tvaddons repo. I can login, though it's slow, but as soon as I do I receive the error listed above. Nothing will load or play from Netflix but will from other sources such as YouTube.

**Comment by Eluminae** [comment]
Same problem here on Archlinux up to date.

**Comment by skylarmt** [comment]
Same issue, RPi 3B+ with OSMC and Kodi 18.2-RC1.

**Comment by wintuxx** [comment]
Try this version:
https://github.com/CastagnaIT/plugin.video.netflix

**Comment by tmsbrdrs** [comment]
Just installed with the same issue. I can login but receive Netflix error. Can navigate menus but cannot play videos.

On February 28, 2019 4:17:45 AM EST, wintuxx <notifications@github.com> wrote:
>Try this version:
>https://github.com/CastagnaIT/plugin.video.netflix
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/asciidisco/plugin.video.netflix/issues/628#issuecomment-468197469

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wintuxx** [comment]
Did you uninstall the old one first?
If not, deinstall the addon, yes to delete all userdata and restart kodi.
then install 0.14.0 again and restart.
if it did not work please post a debug log here in the issues:
https://github.com/CastagnaIT/plugin.video.netflix/issues

**Comment by Eluminae** [comment]
Which 0.14 release are you talking about ? I only see 0.13.19 on both github repositories.

**Comment by tmsbrdrs** [comment]
The highest I'm seeing is 0.13.21. No 0.14 anywhere for me either.

**Comment by wintuxx** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/archive/master.zip

This is the 0.14.0-beta21

**Comment by tmsbrdrs** [comment]
After installing 0.14.0-beta21, I receive the following error. 
"The addon encountered the following error. Exception: AddonSignals
call timed out"
When attempting to play a video, I receive the following. "The addon
encountered the following error:argument "cypherkeyID" for "Encrypt"
must be a string or a bytearray"

**Comment by FolkSong** [comment]
Same problem with Kodi 18.1, Netflix 0.13.22 on Windows.

https://gist.githubusercontent.com/FolkSong/74fd3bc358d074b24d3f83fad0211882/raw/0b5e19939da3b7efd833d5de344946c65c204dbd/kodi.log

I will try the CastagnaIT version.

**Comment by sammyke007** [comment]
Same error after adding widgets in the KODI Netflix menu. Playback works fine however...

**Comment by jakermx** [comment]
The problem is when using widgets, make sure you delay the skin after services boot completely....there is a skin helper on marcelv repository....

**Comment by jakermx** [comment]
> After installing 0.14.0-beta21, I receive the following error. "The addon encountered the following error. Exception: AddonSignals call timed out" When attempting to play a video, I receive the following. "The addon encountered the following error:argument "cypherkeyID" for "Encrypt" must be a string or a bytearray"
> […](#)
> On Thu, 2019-02-28 at 13:59 -0800, wintuxx wrote: https://github.com/CastagnaIT/plugin.video.netflix/archive/master.zip This is the 0.14.0-beta21 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/asciidisc o/plugin.video.netflix","title":"asciidisco/plugin.video.netflix","su btitle":"GitHub repository","main_image_url":" [https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://github.githubassets.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://github.githubassets.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":" ***@***.*** in #628: [https://github.com/CastagnaIT/plugin.video.netflix/archive/master.zip\r\n\r\nThis](https://github.com/CastagnaIT/plugin.video.netflix/archive/master.zip%5Cr%5Cn%5Cr%5CnThis) is the 0.14.0-beta21"}],"action":{"name":"View Issue","url":" [#628 (comment)](https://github.com/asciidisco/plugin.video.netflix/issues/628#issuecomment-468455346) "}}} [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": " [#628 (comment)](https://github.com/asciidisco/plugin.video.netflix/issues/628#issuecomment-468455346) ", "url": " [#628 (comment)](https://github.com/asciidisco/plugin.video.netflix/issues/628#issuecomment-468455346) ", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Enable IPC over HTTP to solvce this issue.

**Comment by Kinc4id** [comment]
> Enable IPC over HTTP to solvce this issue.

I tried this. After that I got an error that the service might not be running. So I restarted the Pi and tried again. Now I got an error parsing msl encodable. The solution I found was deleting $HOME/.kodi/userdata/addon_data/plugin.video.netflix, so I did. I started again and had to put in my email and password again, which I did. I started it again and again I got the error about AddonSignals call timed out. I had to enable IPC over HTTP again. I tried to start again and again I got the error that the service may not be running. Again I restarted the Pi and again I had to enter my password. This time I always get the error that the password is incorrect. It isn't. This is the point where I gave up.

**Comment by LesGirauds** [comment]
Same problem here on a Pi running LibreElec 9.2, Pellucid skin. Interestingly, it doesn't happen on default Estuary skin.

I got around it by configuring a menu item (on Pellucid) to open Netflix from at my (only) profile menu, and avoiding Netflix's main menu. Maybe that's a clue to the problem??
