### ISSUE TITLE
Search function doesn't work

### ISSUE THREAD

**Issue by forenuser** [asciidisco/plugin.video.netflix#645]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by PabloAH** [comment]
It's not working for me either on RPi 3b+ LibreElec 9.0

**Comment by jakermx** [comment]
Please share your log file,I can almost say that you are getting a timeout error on IPC, so please share it

**Comment by PabloAH** [comment]
> Please share your log file,I can almost say that you are getting a timeout error on IPC, so please share it

Yes, it's a timeout

`2019-03-28 20:11:50.577 T:1457771376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 265, in router
                                                return self.show_search_results(params.get('term'))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 362, in show_search_results
                                                'cache': True}))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                              File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
                                              File "/usr/lib/python2.7/httplib.py", line 438, in begin
                                              File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
                                              File "/usr/lib/python2.7/socket.py", line 480, in readline
                                            timeout: timed out
                                            -->End of Python script error report<--`

**Comment by jakermx** [comment]
Add a timeout parameter in urlopen call on this file
 File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1053, in 

From:

call_netflix_service data = urllib2.urlopen(full_url).read()

To:
call_netflix_service data = urllib2.urlopen(full_url,timeout=60).read()

and try again

**Comment by PabloAH** [comment]
yes! that fixed the issue! thanks

**Comment by grazcata** [comment]
thank you
