### ISSUE TITLE
Unable to play content after widevine update

### ISSUE THREAD

**Issue by ericstaal** [asciidisco/plugin.video.netflix#654]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

Netflix does no play a files

### Steps to Reproduce

1. Open netflix
2. try to play anything

**Expected behavior:** 
Video to be played

**Actual behavior:** 
Nothing, went back to the menu

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec 9.0.1 on Pi3b+

## Debug log

https://pastebin.com/20MgFNPu

## Other information

Occured after updateing to latest widevine. It reported an update was available, updated it and the problem occured.
Inputstream adaptive settings can be opend from the pluging however it looks for it in 
/usr/lib/kodi/addons/inputstream.adaptive/

I don;t know why, but this folder does not exists. I only have:
./share/kodi/addons/kodi.binary.instance.inputstream

Could this be solved by changing a setting?

**Comment by jakermx** [comment]
Looks that you dont have KODI 18 running , please share complete log file.

**Comment by jakermx** [comment]
It is not widevine related

2019-03-24 12:02:10.414 T:1546642288   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 244, in load_manifest
2019-03-24 12:02:10.414 T:1546642288   ERROR:     data = self.__decrypt_payload_chunks(resp['payloads'])
2019-03-24 12:02:10.414 T:1546642288   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLv2.py", line 332, in __decrypt_payload_chunks
2019-03-24 12:02:10.414 T:1546642288   ERROR:     decrypted_payload = decrypted_payload[1]['payload']
2019-03-24 12:02:10.414 T:1546642288   ERROR: KeyError: 1

go to addon data directory and delete mpd and json files and restart... it will resolve this issue, it is related to MSLv2 encryption, if this dont work, change your ESN.

**Comment by ericstaal** [comment]
I delete the files, which dit not work. Delete the complete userdats of netflix, and still it did not work.

Logging: 
https://pastebin.com/in2LXMSF

**Comment by jakermx** [comment]
does the "/usr/lib/kodi/addons/inputstream.adaptive/" directory exists?

It should include this files

RPI3:~ # ls /usr/lib/kodi/addons/inputstream.adaptive/
inputstream.adaptive.so         inputstream.adaptive.so.2.3.11
inputstream.adaptive.so.18.0    libssd_wv.so


If not, try to update your kodi to 9.0.1 again.. does not matter you already have 9.01

**Comment by mufflon11** [comment]
got the same error on windows kodi 18.1

**Comment by FloridaStream** [comment]
Working fine for now, last kodi x64 dev release `KodiSetup-20190401-cdab1f19-master`

**Comment by mufflon11** [comment]
Fresh Install KodiSetup-20190401-cdab1f19-master-x64.exe no other plugins 
still not working.. here is a log hope someone can help me :)
https://pastebin.com/B46Ht92H

**Comment by jakermx** [comment]
> Fresh Install KodiSetup-20190401-cdab1f19-master-x64.exe no other plugins
> still not working.. here is a log hope someone can help me :)
> https://pastebin.com/B46Ht92H

Looks that you are having problems on logon, are you able to browse "My List"... if yes, delete the files on userdata directory, just leave the settings file , restar and try to browse from AddOn, not from remote clients, exported links or playlists and share the log please.

**Comment by mufflon11** [comment]
same result here is the new log
https://pastebin.com/XzBUQz1m

**Comment by jakermx** [comment]
reboot it, once KODI Starts wait 5 minutes, then browse netflix addon.... and tell us if you were able to login and browse.

**Comment by mufflon11** [comment]
yes im able to login and browse , but cant play anything

**Comment by jakermx** [comment]
I just  uninstall Kodi RC, delete ProgramFiles\Kodi and C:\Users\Myname\AppData\Roaming\Kodi folders, install 20190401 version, install repository, then netflix addon and  wait until finishes, open and  try to play but I got inputstream adaptive error, it vwas not installed, so I Installed it, open netflix, and it works...

I did it as it...no config changes no extra addons, just as I just tell.... could you do it as it?

If you installed it without deleting the Roaming dirs, you will run in issues.

keep us posted

**Comment by ericstaal** [comment]
> does the "/usr/lib/kodi/addons/inputstream.adaptive/" directory exists?
> 
> It should include this files
> 
> RPI3:~ # ls /usr/lib/kodi/addons/inputstream.adaptive/
> inputstream.adaptive.so inputstream.adaptive.so.2.3.11
> inputstream.adaptive.so.18.0 libssd_wv.so
> 
> If not, try to update your kodi to 9.0.1 again.. does not matter you already have 9.01

The dir does not exists. I found several files in ./storage/.kodi/addons/inputstream.adaptive/:
./storage/.kodi/addons/inputstream.adaptive
./storage/.kodi/addons/inputstream.adaptive/addon.xml
./storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.3.15
./storage/.kodi/addons/inputstream.adaptive/changelog.txt
./storage/.kodi/addons/inputstream.adaptive/libssd_wv.so

Reinstalled inputstream and netflix, but this din't work.

I reinstalled librelec 9.0.1, the directory still didn't exists.

**Comment by jakermx** [comment]
try Netflix 0.14b23, I installed Librelec 9.0.1 from libreelec page, then I upgraded it to LibreELEC-RPi2.arm-9.1-Milhouse-20190327210311-#0327-g5ccaa74, after that I installed Netflix from ZIP and thats it... it worked
[plugin.video.netflix-master(14.0b23).zip](https://github.com/asciidisco/plugin.video.netflix/files/3043371/plugin.video.netflix-master.14.0b23.zip)

**Comment by ericstaal** [comment]
How can I update to a specific version?

**Comment by ericstaal** [comment]
Updated to latest libreelec (LibreELEC-RPi2.arm-9.1-Milhouse-20190403210401-#0403-gbd69cfd.tar) installed netflix 0.14b23, looks rather promising but I still cannot play video:
I kept all settings to default.

2019-04-04 15:19:20.325 T:1790935920 WARNING: Attempt to use invalid handle -1
2019-04-04 15:19:36.583 T:1937302096  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/movie/80223052/
2019-04-04 15:19:36.585 T:1480954736  NOTICE: Creating InputStream
2019-04-04 15:19:37.993 T:1519383408   ERROR: EXCEPTION: argument "line2" for method "ok" must be unicode or str
2019-04-04 15:19:37.993 T:1519383408   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 47, in do_GET
                                                data = self.server.msl_handler.load_manifest(int(params['id'][0]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 45, in error_catching_wrapper
                                                netflix_error=isinstance(exc, MSLError))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/ui/dialogs.py", line 100, in show_error_info
                                                line3=common.get_local_string(30103))
                                            TypeError: argument "line2" for method "ok" must be unicode or str
2019-04-04 15:19:37.994 T:1480954736   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2019-04-04 15:19:37.994 T:1480954736   ERROR: CCurlFile::Open failed with code 400 for http://localhost:39713/manifest?id=80223052:
2019-04-04 15:19:37.994 T:1480954736   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:39713/manifest?id=80223052
2019-04-04 15:19:37.994 T:1480954736   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:39713/manifest?id=80223052)
2019-04-04 15:19:37.997 T:1480954736   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/movie/80223052/]
2019-04-04 15:19:37.997 T:1480954736  NOTICE: CVideoPlayer::OnExit()
2019-04-04 15:19:37.999 T:1519383408   ERROR: Traceback (most recent call last):
2019-04-04 15:19:37.999 T:1519383408   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2019-04-04 15:19:37.999 T:1519383408   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2019-04-04 15:19:37.999 T:1519383408   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-04-04 15:19:38.000 T:1519383408   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
2019-04-04 15:19:38.000 T:1519383408   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
2019-04-04 15:19:38.000 T:1519383408   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-04-04 15:19:38.000 T:1519383408   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-04-04 15:19:38.000 T:1519383408   ERROR: error: [Errno 32] Broken pipe

**Comment by jakermx** [comment]
ok

Let's do something...

Download this file
http://releases.libreelec.tv/LibreELEC-RPi2.arm-9.0.1.img.gz
create the SD card
and  boot with it... once finished boot, configure IP, timezone and then ssh into it
go /storage/.update
type 
    wget http://milhouse.libreelec.tv/builds/master/RPi2/LibreELEC-RPi2.arm-9.1-Milhouse-20190327210311-%230327-g5ccaa74.tar
once done
type 
    chmod 777 /LibreELEC-RPi2.arm-9.1-Milhouse-20190327210311-%230327-g5ccaa74.tar
type 
    reboot
then install from zip the netflix addon
once done... wait 5 mins and then restart...then go addons netflix ... type your credentials, wait for succesful login, and browse for a title... It should work
then  ssh

**Comment by ericstaal** [comment]
I found the cause. 

When connected to a VPN netflix addon dit not play anyhting. Disconnection it from te VPN solved this issue

**Comment by jakermx** [comment]
ok, cool

You might close the issue now...
