### ISSUE TITLE
Exception: Addon Signals call timeout

### ISSUE THREAD

**Issue by artur251** [asciidisco/plugin.video.netflix#729]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Exception: Addon Signals call timeout

### Prerequisites

* [ ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [My profile]
2. [My list]
3. [ERROR]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

2020-05-18 10:28:00.887 T:2320974704   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 34, in set_custom_viewmode
                                                override_partial_setting_id = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 160, in video_list
                                                list_data, extra_data = common.make_call('get_video_list', call_args)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 87, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 152, in make_addonsignals_call
                                                raise Exception('Addon Signals call timeout')
                                            Exception: Addon Signals call timeout

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by chaoscommander** [comment]
This has started happening really often lately, for a few weeks maybe. I sometimes need to try two or three times until I finally get through to playing an episode because on every menu selection there is a 30% chance of getting a timeout error. Maybe the timeout period should be increased by default?
