### ISSUE TITLE
Getting exception: KeyError

### ISSUE THREAD

**Issue by coldspark29** [asciidisco/plugin.video.netflix#731]
Yesterday it was still working. Now I get this error. Am I the only one?

**Comment by citronalco** [comment]
Same here. Plugin fails when selecting the user profile.

```
2020-06-18 09:57:35.923 T:2832196320   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'truths', u'data', u'isLocoSupported']
2020-06-18 09:57:36.000 T:2832196320   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: u'lolomo'
2020-06-18 09:57:36.001 T:2832196320   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 185, in make_return_call
                                                result = call(instance, func, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 208, in call
                                                return func(instance, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_base.py", line 37, in ensure_login
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 95, in activate_profile
                                                self._activate_profile(guid, ignore_update_lolomo_data)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 119, in _activate_profile
                                                self.auth_url = website.extract_session_data(response)['auth_url']
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 124, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'
2020-06-18 09:57:36.066 T:2449466080   ERROR: [plugin.video.netflix (102)] IPC call activate_profile returned KeyError: u'lolomo'
2020-06-18 09:57:36.072 T:2449466080   ERROR: [plugin.video.netflix (102)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 34, in set_custom_viewmode
                                                override_partial_setting_id = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 93, in home
                                                if not activate_profile(self.params['switch_profile_guid']):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 148, in activate_profile
                                                common.make_call('activate_profile', guid)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 89, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 162, in make_addonsignals_call
                                                _raise_for_error(callname, result)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 175, in _raise_for_error
                                                raise Exception(result['error'])
                                            Exception: KeyError
```

**Comment by coldspark29** [comment]
It seems to be an issue for everyone. It is all over the Kodi Forum. Hoping for a fix soon!

**Comment by saba1970** [comment]
I have the same issue after updating the Netflix addon.

**Comment by fonziemedia** [comment]
Same issue here

**Comment by phisch92** [comment]
Same issue here

**Comment by coldspark29** [comment]
I am assuming Netflix has changed something with the API key and the Kodi plugin has to be changed accordingly. We just have to wait. It might be good if users good change this API key themselves in the settings, but I have no idea whether that is possible or not. For me it is good. Im in the examination phase and Prison Break is just too addictive xD

**Comment by phisch92** [comment]
I tried:
[ ] Logout and Login again,
[ ] downgrade the addon and
[ ] tested inputstream, which works fine.
but was not able to start or select a movie via Netflix-Addon.

**Comment by coldspark29** [comment]
Here is the reason: https://forum.kodi.tv/showthread.php?tid=329767&pid=2958081#pid2958081

It seems that Netflix has changed it's website layout and remember that this plugin is just a web scraper, that fetches the links via BeautifulSoup probably. As soon as the website changes, the code has be adjusted. It might take a month to fix this, depending on when the developer finds the time. There is another plugin mentioned in the above thread provides a Netflix functionality.

**Comment by kurt636** [comment]
It's working for me...
