### ISSUE TITLE
Netflix Addon Notification Error: Exception: KeyError

### ISSUE THREAD

**Issue by og-python-scripts** [asciidisco/plugin.video.netflix#732]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ x] Are you running the latest version?

### Description

[Description of the bug or feature]
When I start the application, it asks me to login.  After inputting my valid credentials, the application pops up the error notification screen that states "Exception: KeyError" and to review the kodi.log file.
### Steps to Reproduce

1. [First Step] Install most recent addon
2. [Second Step] Login with your account credentials
3. [and so on...] immediately met with error

**Expected behavior:** [What you expected to happen]
able to login to netflix successfully and able to select account to use to view categories.
**Actual behavior:** [What actually happened]
I am met with the "Exception: KeyError"
## Context (Environment)
RaspberryPi - Libreelec && Windows 10
### Installation

* [x ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [x ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
1) LibreElec on RaspberryPi 2b and 3
2) Windows 10 with Kodi installed from windows store
3) Windows 10 with Kodi installed from direct download from kodi webpage.

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/4799950/kodi.log)
## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]
I am not sure, I have searched google for similar errors and some mention something about netflix headers being sent and trying to add a file called NeflixSession.py
### Screenshots

[Please add a screenshot if that helps understanding your problem]
![image](https://user-images.githubusercontent.com/47901278/85048867-a0592f00-b12f-11ea-9eab-bfce234e7fac.png)

[You can erase any parts of this template not applicable to your Issue.]

**Comment by og-python-scripts** [comment]
*NetflixSession.py

**Comment by xoref** [comment]
Same for Ubuntu with latest Kodi & plugin version.

**Comment by Xeli** [comment]
I've got the same issue, logs give me this stacktrace:
```
2020-06-18 19:30:36.827 T:139865837029120   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'apiUrl']
2020-06-18 19:30:36.827 T:139865837029120   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'core', u'assets', u'core']
2020-06-18 19:30:36.827 T:139865837029120   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'uiVersion']
2020-06-18 19:30:37.654 T:139865516517120   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-06-18 19:30:37.674 T:139869033965952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2020-06-18 19:30:38.182 T:139865837029120   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'truths', u'data', u'isLocoSupported']
2020-06-18 19:30:42.510 T:139865837029120   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_access.py", line 91, in _login
                                                website.extract_session_data(login_response, validate=True, update_profiles=True)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 124, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'
2020-06-18 19:30:42.510 T:139865837029120   ERROR: [plugin.video.netflix (0)] Background services do not start due to the following error
2020-06-18 19:30:42.511 T:139865837029120   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 73, in init_servers
                                                self._init_server(server)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 94, in _init_server
                                                (self.HOST_ADDRESS, select_port(server['name']))
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/http_server.py", line 59, in __init__
                                                self.netflix_session = NetflixSession()
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 47, in __init__
                                                self.prefetch_login()
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_access.py", line 44, in prefetch_login
                                                self._login()
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_access.py", line 91, in _login
                                                website.extract_session_data(login_response, validate=True, update_profiles=True)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/richard/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 124, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'
```

**Comment by je-marshall** [comment]
Can confirm the same error, running:
Starting Kodi (18.3 Git:20190619-89472b7d69). Platform: Windows NT x86 64-bit
Using Release Kodi x64 build
Kodi compiled 2019-06-28 by MSVC 191627031 for Windows NT x86 64-bit version 10.0 (0x0A000006)
Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362
FFmpeg version/source: 4.0.3-Kodi

plugin.video.netflix v1.4.1 installed

Possibly related to some change made by Netflix, similar to https://github.com/asciidisco/plugin.video.netflix/issues/643 ?

**Comment by poddardelhi** [comment]
same here, the issue started after I changed my password and now when I am trying to re-login with new pwd. It complains.


`2020-06-20 10:36:24.191 T:1449571200  NOTICE: DecodeJpeg: unable to decode http://mirrors.kodi.tv/addons/leia/plugin.video.ng/resources/media/ss3.jpg 704x540
2020-06-20 10:36:42.426 T:1559511936   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-06-20 10:36:42.444 T:1936804288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2020-06-20 10:37:25.161 T:1399214976   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'apiUrl']
2020-06-20 10:37:25.162 T:1399214976   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'core', u'assets', u'core']
2020-06-20 10:37:25.162 T:1399214976   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'uiVersion']
2020-06-20 10:37:26.913 T:1399214976   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'truths', u'data', u'isLocoSupported']
2020-06-20 10:37:28.281 T:1399214976   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_access.py", line 91, in _login
                                                website.extract_session_data(login_response, validate=True, update_profiles=True)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 124, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'
2020-06-20 10:37:28.281 T:1399214976   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: u'lolomo'
2020-06-20 10:37:28.283 T:1399214976   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 185, in make_return_call
                                                result = call(instance, func, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 209, in call
                                                return func(instance)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_access.py", line 77, in login
                                                return self._login(modal_error_message=True)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_access.py", line 91, in _login
                                                website.extract_session_data(login_response, validate=True, update_profiles=True)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 124, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'`

**Comment by youdouble** [comment]
> Can confirm the same error, running:
> Starting Kodi (18.3 Git:20190619-89472b7d69). Platform: Windows NT x86 64-bit
> Using Release Kodi x64 build
> Kodi compiled 2019-06-28 by MSVC 191627031 for Windows NT x86 64-bit version 10.0 (0x0A000006)
> Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362
> FFmpeg version/source: 4.0.3-Kodi
> 
> plugin.video.netflix v1.4.1 installed
> 
> Possibly related to some change made by Netflix, similar to #643 ?

I am having the same issue, and figured it was something similar to #643 as well. 

Both machines here are not working, as of a week or so? Not sure the exact date. 

Hardware: RPI 3 & 4 
OS: LibreELEC (official): 9.2.1 (RPi4.arm)
Plugin: Netflix 1.4.1

**Comment by og-python-scripts** [comment]
status update:

It looks like Netflix is working again. There was a notification of an update that was available through the Kodi Dashboard.

Libreelec applied the update automatically, and in addition I updated some type of google player addon and it seems to work there.

For my windows kodi, i had to manually install the available update because the automatic method failed. once I installed it and allowed the login and background services to start, the addon was able to function properly.  The update that was applied was v1.5.0 

Was there any details as to what changed to fix this? was this due to the layout of Netflix's page changing and scrappers had to be tuned accordingly?  Request header structure had to be reconfigured? 

This was the version information of the addon that resolved this:
![image](https://user-images.githubusercontent.com/47901278/85467196-9d52aa00-b546-11ea-806e-9ea13ce8c1c5.png)
